### ISSUE TITLE
Ditto 2.0.1: Failed to parse JWT! - ExpiredJwtException

### ISSUE THREAD

**Issue by w4tsn** [eclipse/ditto#1073]
With Ditto 2.0.1 I'm seeing INFO level messages associated with exceptions printed in the logs. I don't think those exceptions should be printed into the log. I suppose one of the clients does not update it's JWT, hence it's invalid. The INFO is OK, but instead of the exception it should probably show more details in the INFO message.

```
gateway_1        | 	io.jsonwebtoken.ExpiredJwtException: JWT expired at 2021-05-28T08:08:52Z. Current time: 2021-05-28T08:11:03Z, a difference of 131436 milliseconds.  Allowed clock skew: 0 milliseconds.
gateway_1        | 	at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:448)
gateway_1        | 	at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:550)
gateway_1        | 	at io.jsonwebtoken.impl.DefaultJwtParser.parseClaimsJws(DefaultJwtParser.java:610)
gateway_1        | 	at io.jsonwebtoken.impl.ImmutableJwtParser.parseClaimsJws(ImmutableJwtParser.java:173)
gateway_1        | 	at org.eclipse.ditto.gateway.service.security.authentication.jwt.DefaultJwtValidator.validateWithPublicKey(DefaultJwtValidator.java:84)
gateway_1        | 	at org.eclipse.ditto.gateway.service.security.authentication.jwt.DefaultJwtValidator.tryToValidateWithPublicKey(DefaultJwtValidator.java:72)
gateway_1        | 	at org.eclipse.ditto.gateway.service.security.authentication.jwt.DefaultJwtValidator.lambda$validate$0(DefaultJwtValidator.java:61)
gateway_1        | 	at org.eclipse.ditto.gateway.service.security.authentication.jwt.DefaultJwtValidator$$Lambda$4284/0x00000000c001b6d0.apply(Unknown Source)
gateway_1        | 	at java.base/java.util.Optional.map(Optional.java:265)
gateway_1        | 	at org.eclipse.ditto.gateway.service.security.authentication.jwt.DefaultJwtValidator.lambda$validate$2(DefaultJwtValidator.java:61)
gateway_1        | 	at org.eclipse.ditto.gateway.service.security.authentication.jwt.DefaultJwtValidator$$Lambda$3335/0x00000000ec05c7d0.apply(Unknown Source)
gateway_1        | 	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:680)
gateway_1        | 	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:658)
gateway_1        | 	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2094)
gateway_1        | 	at org.eclipse.ditto.gateway.service.security.authentication.jwt.DefaultJwtValidator.validate(DefaultJwtValidator.java:60)
gateway_1        | 	at org.eclipse.ditto.gateway.service.security.authentication.jwt.JwtAuthenticationProvider.getAuthenticationResult(JwtAuthenticationProvider.java:132)
gateway_1        | 	at org.eclipse.ditto.gateway.service.security.authentication.jwt.JwtAuthenticationProvider.tryToAuthenticate(JwtAuthenticationProvider.java:122)
gateway_1        | 	at org.eclipse.ditto.gateway.service.security.authentication.TimeMeasuringAuthenticationProvider.authenticate(TimeMeasuringAuthenticationProvider.java:65)
gateway_1        | 	at org.eclipse.ditto.gateway.service.security.authentication.AuthenticationChain$AuthResultAccumulator.andThen(AuthenticationChain.java:176)
gateway_1        | 	at org.eclipse.ditto.gateway.service.security.authentication.AuthenticationChain.lambda$authenticate$0(AuthenticationChain.java:95)
gateway_1        | 	at org.eclipse.ditto.gateway.service.security.authentication.AuthenticationChain$$Lambda$3012/0x00000000500a44a0.apply(Unknown Source)
gateway_1        | 	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072)
gateway_1        | 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
gateway_1        | 	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:53)
gateway_1        | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
gateway_1        | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
gateway_1        | 	at java.base/java.lang.Thread.run(Thread.java:836)

```

**Comment by thjaeckle** [comment]
I agree and created PR #1075
