### ISSUE TITLE
Performance drop in gateway service with many JWT providers

### ISSUE THREAD

**Issue by w4tsn** [eclipse/ditto#1082]
After the upgrade from Ditto 1.5.x to 2.0.1 I'm experiencing massive performance issues in the gateway service. The load increased by around 300%, after 5 minutes of runtime all requests are answered with a 503, the logs are full of timeout errors, JWT errors and warnings about increasingly slow HTTP connections. Let's go into the details what is happening:

First the cluster starts and reports an overall OK status. New log entries appear of INFO level stating that JWTs are successfully validated (this is already somewhat "slow" compared to the amount of JWT-based requests that should go through). No warnings or errors yet. The business applications already show that requests are really slow, although most still succeed. After around 3 minutes of runtime the problems begin to pile up. In the log of the gateway service the first warnings about 60s timeouts and slow HTTP connections show up. The timeouts as well as the HTTP warnings grow larger and larger in both their "overdue" time and quantity in the log. Then the successful JWT INFO messages disappear and are replaced by more and more JWT invalidation errors, because the JWTs provided are expired. The duration since expiration increases over time as if either the provided JWTs don't get refreshed (this I doubt) or messages get validated increasingly late.

Details about my setup
---

The special case of my setup is that I'm using a lot of issuers. 20 by the time of this writing. This is because every auth realm has it's own distinct issuer endpoint. Maybe that is a problem or at least something not accounted for in the tests?

How I upgraded
---

I changed the container image version numbers and updated the JWT issuer configuration, such that the newly introduced object level with the `issuer` key is accounted for. 

I've yet to monitor the whole log of the cluster. Maybe there are other issues in other services as well. I only took a brief look into the cluster log, because that one is massive. The gateway log stood out to me, so I investigated this one first.

Logs
---

Some log output after a restart

```
gateway_1        | 2021-06-02 08:58:24,864 DEBUG [e7427bde-4460-4186-94b1-d758f9408a7a] o.e.d.g.s.e.a.HttpRequestActor akka://ditto-cluster/user/$yb - Got <devops.responses:aggregatedResponse> message.
gateway_1        | 2021-06-02 08:58:24,865 DEBUG [e7427bde-4460-4186-94b1-d758f9408a7a] o.e.d.g.s.e.a.HttpRequestActor akka://ditto-cluster/user/$yb - Enhancing response with external headers <ImmutableDittoHeaders [{correlation-id=e7427bde-4460-4186-94b1-d758f9408a7a, response-required=false}]>.
gateway_1        | 2021-06-02 08:58:24,865 DEBUG [] o.e.d.g.s.e.a.HttpRequestActor akka://ditto-cluster/user/$yb - Responding with HTTP response code <200>.
gateway_1        | 2021-06-02 08:58:24,865 DEBUG [] o.e.d.g.s.e.a.HttpRequestActor akka://ditto-cluster/user/$yb - Responding with entity <HttpEntity.Strict(application/json,130 bytes total)>.
gateway_1        | 2021-06-02 08:58:24,928 DEBUG [] o.e.d.b.s.d.DevOpsCommandsActor$DevOpsCommandResponseCorrelationActor akka://ditto-cluster/user/devOpsCommandsActor/e7427bde-4460-4186-94b1-d758f9408a7a - stopped
gateway_1        | 2021-06-02 08:58:24,947 INFO  [ab869c23-944f-464d-b5ba-db7fd9e999a3] o.e.d.g.s.e.d.RequestResultLoggingDirective  - StatusCode of request PUT '/devops/logging/gateway' was: 200
gateway_1        | 2021-06-02 08:58:24,947 DEBUG [] o.e.d.g.s.e.a.HttpRequestActor akka://ditto-cluster/user/$yb - stopped
gateway_1        | 2021-06-02 08:58:25,029 DEBUG [ab869c23-944f-464d-b5ba-db7fd9e999a3] o.e.d.g.s.e.d.RequestResultLoggingDirective  - Raw request URI was: Raw-Request-URI: /devops/logging/gateway
gateway_1        | 2021-06-02 08:58:25,030 DEBUG [ab869c23-944f-464d-b5ba-db7fd9e999a3] o.e.d.g.s.e.d.RequestTimeoutHandlingDirective  - Finished timer <StartedKamonTimer [name=roundtrip_http, tags={ditto.request.path=/other, ditto.statusCode=200, ditto.request.method=PUT, segment=overall}, onStopHandlers=[org.eclipse.ditto.internal.utils.metrics.instruments.timer.OnStopHandler@60c806b0], segments={}, startTimestamp=17602639006485774, stoppedTimer=StoppedKamonTimer [name=roundtrip_http, tags={ditto.request.path=/other, ditto.statusCode=200, ditto.request.method=PUT, segment=overall}, startTimestamp=17602639006485774, endTimestamp=17602644501881223]]> with status <200>.
gateway_1        | 2021-06-02 08:58:25,032 WARN  [ab869c23-944f-464d-b5ba-db7fd9e999a3] o.e.d.g.s.e.d.RequestTimeoutHandlingDirective  - Encountered slow HTTP request which took over <1000> ms: <5495> ms!
gateway_1        | 2021-06-02 08:58:25,375 DEBUG [e3467eed-6adb-47a1-b2e3-25e294a95d71] o.e.d.g.s.e.d.CorrelationIdEnsuringDirective  - Created new correlation ID <e3467eed-6adb-47a1-b2e3-25e294a95d71>.
gateway_1        | 2021-06-02 08:58:25,376 DEBUG [] o.e.d.i.u.t.TraceUriGenerator  - Generated traceUri for '/api/2/things/c0000:CA941651884F8042/features/SiteStatus/properties/status/ConnectionStatus': 'TraceInformation{traceUri='/api/2/things/x', tags={ditto.request.path=/api/2/things/x/features/x}}'
gateway_1        | 2021-06-02 08:58:25,378 DEBUG [e3467eed-6adb-47a1-b2e3-25e294a95d71] o.e.d.g.s.e.d.RequestTimeoutHandlingDirective  - Started mutable timer <StartedKamonTimer [name=roundtrip_http, tags={ditto.request.path=/api/2/things/x/features/x, ditto.request.method=PUT, segment=overall}, onStopHandlers=[org.eclipse.ditto.internal.utils.metrics.instruments.timer.OnStopHandler@e295c292], segments={}, startTimestamp=17602644849946821, stoppedTimer=null]>.
gateway_1        | 2021-06-02 08:58:25,937 DEBUG [9e2726fb-70be-417d-a910-6eb754f83216] o.e.d.g.s.e.d.CorrelationIdEnsuringDirective  - Created new correlation ID <9e2726fb-70be-417d-a910-6eb754f83216>.
gateway_1        | 2021-06-02 08:58:25,939 DEBUG [] o.e.d.i.u.t.TraceUriGenerator  - Generated traceUri for '/api/2/things/c0007:56BE111F4CAD7282/features/DifferentialPressure/properties/status': 'TraceInformation{traceUri='/api/2/things/x', tags={ditto.request.path=/api/2/things/x/features/x}}'
gateway_1        | 2021-06-02 08:58:25,940 DEBUG [9e2726fb-70be-417d-a910-6eb754f83216] o.e.d.g.s.e.d.RequestTimeoutHandlingDirective  - Started mutable timer <StartedKamonTimer [name=roundtrip_http, tags={ditto.request.path=/api/2/things/x/features/x, ditto.request.method=PUT, segment=overall}, onStopHandlers=[org.eclipse.ditto.internal.utils.metrics.instruments.timer.OnStopHandler@ffcb5a64], segments={}, startTimestamp=17602645412157647, stoppedTimer=null]>.
gateway_1        | 2021-06-02 08:58:25,945 INFO  [541878fa-6a00-4160-b7a4-9ebfaa1b391a] o.e.d.g.s.s.a.j.JwtAuthenticationProvider  - Completed JWT authentication successfully.
gateway_1        | 2021-06-02 08:58:26,351 INFO  [c1aee384-057e-4b12-be71-937c945e4ef9] o.e.d.g.s.s.a.j.JwtAuthenticationProvider  - Completed JWT authentication successfully.
```

Log output after 10 minutes

```
gateway_1        | 2021-06-02 08:53:21,438 WARN  [6b3d8bbc-7836-43a8-bf4c-7ebe53d7b6c0] o.e.d.g.s.e.d.RequestTimeoutHandlingDirective  - Request <GET /api/2/search/things?filter=eq(features/Certificate/properties/status/subjectName,%22g0020%22)> timed out after <PT1M>!
gateway_1        | 2021-06-02 08:53:21,438 INFO  [6b3d8bbc-7836-43a8-bf4c-7ebe53d7b6c0] o.e.d.g.s.e.d.RequestTimeoutHandlingDirective  - Status code of request <GET /api/2/search/things?filter=eq(features/Certificate/properties/status/subjectName,%22g0020%22)> was <503>.
gateway_1        | 2021-06-02 08:53:21,438 DEBUG [6b3d8bbc-7836-43a8-bf4c-7ebe53d7b6c0] o.e.d.g.s.e.d.RequestTimeoutHandlingDirective  - Raw request URI was <Raw-Request-URI: /api/2/search/things?filter=eq(features/Certificate/properties/status/subjectName,%22g0020%22)>.
gateway_1        | 2021-06-02 08:53:21,438 DEBUG [6b3d8bbc-7836-43a8-bf4c-7ebe53d7b6c0] o.e.d.g.s.e.d.RequestTimeoutHandlingDirective  - Finished mutable timer <StartedKamonTimer [name=roundtrip_http, tags={ditto.request.path=/api/2/search/things/x, ditto.statusCode=503, ditto.request.method=GET, segment=overall}, onStopHandlers=[org.eclipse.ditto.internal.utils.metrics.instruments.timer.OnStopHandler@b5eae7a], segments={}, startTimestamp=17602280892355908, stoppedTimer=StoppedKamonTimer [name=roundtrip_http, tags={ditto.request.path=/api/2/search/things/x, ditto.statusCode=503, ditto.request.method=GET, segment=overall}, startTimestamp=17602280892355908, endTimestamp=17602340910398057]]> after a request timeout with status <503>
gateway_1        | 2021-06-02 08:53:21,540 INFO  [] o.e.d.g.s.s.a.j.DefaultJwtValidator  - Failed to parse JWT!
gateway_1        | io.jsonwebtoken.ExpiredJwtException: JWT expired at 2021-06-02T06:52:01Z. Current time: 2021-06-02T06:53:21Z, a difference of 80540 milliseconds.  Allowed clock skew: 0 milliseconds.
gateway_1        | 	at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:448)
gateway_1        | 	at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:550)
gateway_1        | 	at io.jsonwebtoken.impl.DefaultJwtParser.parseClaimsJws(DefaultJwtParser.java:610)
gateway_1        | 	at io.jsonwebtoken.impl.ImmutableJwtParser.parseClaimsJws(ImmutableJwtParser.java:173)
gateway_1        | 	at org.eclipse.ditto.gateway.service.security.authentication.jwt.DefaultJwtValidator.validateWithPublicKey(DefaultJwtValidator.java:84)
gateway_1        | 	at org.eclipse.ditto.gateway.service.security.authentication.jwt.DefaultJwtValidator.tryToValidateWithPublicKey(DefaultJwtValidator.java:72)
gateway_1        | 	at org.eclipse.ditto.gateway.service.security.authentication.jwt.DefaultJwtValidator.lambda$validate$0(DefaultJwtValidator.java:61)
gateway_1        | 	at org.eclipse.ditto.gateway.service.security.authentication.jwt.DefaultJwtValidator$$Lambda$4271/0x0000000088013010.apply(Unknown Source)
gateway_1        | 	at java.base/java.util.Optional.map(Optional.java:265)
gateway_1        | 	at org.eclipse.ditto.gateway.service.security.authentication.jwt.DefaultJwtValidator.lambda$validate$2(DefaultJwtValidator.java:61)
gateway_1        | 	at org.eclipse.ditto.gateway.service.security.authentication.jwt.DefaultJwtValidator$$Lambda$4221/0x0000000080015d70.apply(Unknown Source)
gateway_1        | 	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:680)
gateway_1        | 	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:658)
gateway_1        | 	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2094)
gateway_1        | 	at org.eclipse.ditto.gateway.service.security.authentication.jwt.DefaultJwtValidator.validate(DefaultJwtValidator.java:60)
gateway_1        | 	at org.eclipse.ditto.gateway.service.security.authentication.jwt.JwtAuthenticationProvider.getAuthenticationResult(JwtAuthenticationProvider.java:132)
gateway_1        | 	at org.eclipse.ditto.gateway.service.security.authentication.jwt.JwtAuthenticationProvider.tryToAuthenticate(JwtAuthenticationProvider.java:122)
gateway_1        | 	at org.eclipse.ditto.gateway.service.security.authentication.TimeMeasuringAuthenticationProvider.authenticate(TimeMeasuringAuthenticationProvider.java:65)
gateway_1        | 	at org.eclipse.ditto.gateway.service.security.authentication.AuthenticationChain$AuthResultAccumulator.andThen(AuthenticationChain.java:176)
gateway_1        | 	at org.eclipse.ditto.gateway.service.security.authentication.AuthenticationChain.lambda$authenticate$0(AuthenticationChain.java:95)
gateway_1        | 	at org.eclipse.ditto.gateway.service.security.authentication.AuthenticationChain$$Lambda$2792/0x00000000701f0fb0.apply(Unknown Source)
gateway_1        | 	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072)
gateway_1        | 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
gateway_1        | 	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:53)
gateway_1        | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
gateway_1        | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
gateway_1        | 	at java.base/java.lang.Thread.run(Thread.java:836)
gateway_1        | 2021-06-02 08:53:21,540 DEBUG [418abbd0-34ed-44f4-8ee0-41d6ce126299] o.e.d.g.s.s.a.j.JwtAuthenticationProvider  - The JWT is invalid.
gateway_1        | io.jsonwebtoken.ExpiredJwtException: JWT expired at 2021-06-02T06:52:01Z. Current time: 2021-06-02T06:53:21Z, a difference of 80540 milliseconds.  Allowed clock skew: 0 milliseconds.
gateway_1        | 	at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:448)
gateway_1        | 	at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:550)
gateway_1        | 	at io.jsonwebtoken.impl.DefaultJwtParser.parseClaimsJws(DefaultJwtParser.java:610)
gateway_1        | 	at io.jsonwebtoken.impl.ImmutableJwtParser.parseClaimsJws(ImmutableJwtParser.java:173)
gateway_1        | 	at org.eclipse.ditto.gateway.service.security.authentication.jwt.DefaultJwtValidator.validateWithPublicKey(DefaultJwtValidator.java:84)
gateway_1        | 	at org.eclipse.ditto.gateway.service.security.authentication.jwt.DefaultJwtValidator.tryToValidateWithPublicKey(DefaultJwtValidator.java:72)
gateway_1        | 	at org.eclipse.ditto.gateway.service.security.authentication.jwt.DefaultJwtValidator.lambda$validate$0(DefaultJwtValidator.java:61)
gateway_1        | 	at org.eclipse.ditto.gateway.service.security.authentication.jwt.DefaultJwtValidator$$Lambda$4271/0x0000000088013010.apply(Unknown Source)
gateway_1        | 	at java.base/java.util.Optional.map(Optional.java:265)
gateway_1        | 	at org.eclipse.ditto.gateway.service.security.authentication.jwt.DefaultJwtValidator.lambda$validate$2(DefaultJwtValidator.java:61)
gateway_1        | 	at org.eclipse.ditto.gateway.service.security.authentication.jwt.DefaultJwtValidator$$Lambda$4221/0x0000000080015d70.apply(Unknown Source)
gateway_1        | 	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:680)
gateway_1        | 	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:658)
gateway_1        | 	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2094)
gateway_1        | 	at org.eclipse.ditto.gateway.service.security.authentication.jwt.DefaultJwtValidator.validate(DefaultJwtValidator.java:60)
gateway_1        | 	at org.eclipse.ditto.gateway.service.security.authentication.jwt.JwtAuthenticationProvider.getAuthenticationResult(JwtAuthenticationProvider.java:132)
gateway_1        | 	at org.eclipse.ditto.gateway.service.security.authentication.jwt.JwtAuthenticationProvider.tryToAuthenticate(JwtAuthenticationProvider.java:122)
gateway_1        | 	at org.eclipse.ditto.gateway.service.security.authentication.TimeMeasuringAuthenticationProvider.authenticate(TimeMeasuringAuthenticationProvider.java:65)
gateway_1        | 	at org.eclipse.ditto.gateway.service.security.authentication.AuthenticationChain$AuthResultAccumulator.andThen(AuthenticationChain.java:176)
gateway_1        | 	at org.eclipse.ditto.gateway.service.security.authentication.AuthenticationChain.lambda$authenticate$0(AuthenticationChain.java:95)
gateway_1        | 	at org.eclipse.ditto.gateway.service.security.authentication.AuthenticationChain$$Lambda$2792/0x00000000701f0fb0.apply(Unknown Source)
gateway_1        | 	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072)
gateway_1        | 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
gateway_1        | 	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:53)
gateway_1        | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
gateway_1        | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
gateway_1        | 	at java.base/java.lang.Thread.run(Thread.java:836)
```

**Comment by thjaeckle** [comment]
Hm, maybe try increasing the cache size for OpenId connect public keys:
https://github.com/eclipse/ditto/blob/8270f5a6fc2dcae65191c6795f8f6763f9f9e669/gateway/service/src/main/resources/gateway.conf#L277

This is by default only 32
Maybe more than one public keys are retrieved per issuer and the size is not sufficient so that the public keys have to be retrieved too often (in the worst case per http request one public key retrieval).
But this is only a wild guess ;)

**Comment by thjaeckle** [comment]
@w4tsn did you find out what the problem was here?

**Comment by w4tsn** [comment]
Hey @thjaeckle, I confirm that increasing the cache size for public keys solves the issue.

I'm still seeing 502 Bad Gateway errors, where there were none before the upgrade but that's another issue. Probably even just some quirk with our specific deployment.

Also the gateway service still reports Slow HTTP connections. My guess is, that those were slow even before the upgrade but ditto starts to complain about this since 2.0?
