### ISSUE TITLE
Maven build error with mockito

### ISSUE THREAD

**Issue by jack04060201** [eclipse/ditto#1105]
Hello! 
I'm trying to use maven to build Ditto. "sudo mvn clean install"
But always get error n stop at policies.service
I have been search error but not get some useful info.
Anyone can resolve it?
Thanks

### Device:
Ubuntu 18.04 on VMware workstation
maven 3.6.0
docker-compose 1.17.1
docker 1.5-1
jdk 1.11

This is part of log:
```
[INFO] Running org.eclipse.ditto.policies.service.persistence.actors.strategies.commands.SubjectExpiryAdjustmentTest
[ERROR] Tests run: 8, Failures: 6, Errors: 0, Skipped: 0, Time elapsed: 0.071 s <<< FAILURE! - in org.eclipse.ditto.policies.service.persistence.actors.strategies.commands.SubjectExpiryAdjustmentTest
[ERROR] org.eclipse.ditto.policies.service.persistence.actors.strategies.commands.SubjectExpiryAdjustmentTest.roundingUpToFifteenMinutes  Time elapsed: 0.023 s  <<< FAILURE!
org.mockito.exceptions.verification.WantedButNotInvoked: 

Wanted but not invoked:
dummy.onMutation(
    <any>,
    <Capturing argument>,
    ModifySubjectResponse [dittoHeaders=ImmutableDittoHeaders [{etag="hash:2a09937d", response-required=false}], responseType=policies.responses:modifySubject, httpStatus=HttpStatus [code=201, category=SUCCESS], policyId=com.example:testPolicy, label=custom, subjectCreated=ImmutableSubject [subjectId=integration:this-is-me, subjectType=mySubjectType, subjectExpiry=2021-06-30T04:15:00Z, subjectAnnouncement=null], subjectId=integration:this-is-me],
    <any boolean>,
    false
);
-> at org.eclipse.ditto.policies.service.persistence.actors.strategies.commands.AbstractPolicyCommandStrategyTest.assertModificationResult(AbstractPolicyCommandStrategyTest.java:158)

However, there was exactly 1 interaction with this mock:
dummy.onError(
    org.eclipse.ditto.policies.model.SubjectExpiryInvalidException [message='Subject expiry timestamp '2021-06-30T04:15:00Z' is not valid.', errorCode=policies:subjectexpiry.invalid, httpStatus=HttpStatus [code=400, category=CLIENT_ERROR], description='It must not be in the past, please adjust to a timestamp in the future.', href=null, dittoHeaders=ImmutableDittoHeaders [{}]],
    ModifySubject [type=policies.commands:modifySubject, dittoHeaders=ImmutableDittoHeaders [{}], policyId=com.example:testPolicy, label=custom, subject=ImmutableSubject [subjectId=integration:this-is-me, subjectType=mySubjectType, subjectExpiry=2021-06-30T04:07:03Z, subjectAnnouncement=null]]
);
-> at org.eclipse.ditto.internal.utils.persistentactors.results.ErrorResult.accept(ErrorResult.java:44)


	at org.eclipse.ditto.policies.service.persistence.actors.strategies.commands.SubjectExpiryAdjustmentTest.doTestSubjectExpiryAdjustment(SubjectExpiryAdjustmentTest.java:181)
	at org.eclipse.ditto.policies.service.persistence.actors.strategies.commands.SubjectExpiryAdjustmentTest.roundingUpToFifteenMinutes(SubjectExpiryAdjustmentTest.java:101)

[ERROR] org.eclipse.ditto.policies.service.persistence.actors.strategies.commands.SubjectExpiryAdjustmentTest.roundingUpToOneHour  Time elapsed: 0.006 s  <<< FAILURE!
org.mockito.exceptions.verification.WantedButNotInvoked: 

Wanted but not invoked:
dummy.onMutation(
    <any>,
    <Capturing argument>,
    ModifySubjectResponse [dittoHeaders=ImmutableDittoHeaders [{etag="hash:2a0ada71", response-required=false}], responseType=policies.responses:modifySubject, httpStatus=HttpStatus [code=201, category=SUCCESS], policyId=com.example:testPolicy, label=custom, subjectCreated=ImmutableSubject [subjectId=integration:this-is-me, subjectType=mySubjectType, subjectExpiry=2021-06-30T05:00:00Z, subjectAnnouncement=null], subjectId=integration:this-is-me],
    <any boolean>,
    false
);
-> at org.eclipse.ditto.policies.service.persistence.actors.strategies.commands.AbstractPolicyCommandStrategyTest.assertModificationResult(AbstractPolicyCommandStrategyTest.java:158)

However, there was exactly 1 interaction with this mock:
dummy.onError(
    org.eclipse.ditto.policies.model.SubjectExpiryInvalidException [message='Subject expiry timestamp '2021-06-30T05:00:00Z' is not valid.', errorCode=policies:subjectexpiry.invalid, httpStatus=HttpStatus [code=400, category=CLIENT_ERROR], description='It must not be in the past, please adjust to a timestamp in the future.', href=null, dittoHeaders=ImmutableDittoHeaders [{}]],
    ModifySubject [type=policies.commands:modifySubject, dittoHeaders=ImmutableDittoHeaders [{}], policyId=com.example:testPolicy, label=custom, subject=ImmutableSubject [subjectId=integration:this-is-me, subjectType=mySubjectType, subjectExpiry=2021-06-30T04:55:36.090714Z, subjectAnnouncement=null]]
);
-> at org.eclipse.ditto.internal.utils.persistentactors.results.ErrorResult.accept(ErrorResult.java:44)


	at org.eclipse.ditto.policies.service.persistence.actors.strategies.commands.SubjectExpiryAdjustmentTest.doTestSubjectExpiryAdjustment(SubjectExpiryAdjustmentTest.java:181)
	at org.eclipse.ditto.policies.service.persistence.actors.strategies.commands.SubjectExpiryAdjustmentTest.roundingUpToOneHour(SubjectExpiryAdjustmentTest.java:116)

[ERROR] org.eclipse.ditto.policies.service.persistence.actors.strategies.commands.SubjectExpiryAdjustmentTest.roundingUpToTenSeconds  Time elapsed: 0.007 s  <<< FAILURE!
org.mockito.exceptions.verification.WantedButNotInvoked: 

Wanted but not invoked:
dummy.onMutation(
    <any>,
    <Capturing argument>,
    ModifySubjectResponse [dittoHeaders=ImmutableDittoHeaders [{etag="hash:2a095f6b", response-required=false}], responseType=policies.responses:modifySubject, httpStatus=HttpStatus [code=201, category=SUCCESS], policyId=com.example:testPolicy, label=custom, subjectCreated=ImmutableSubject [subjectId=integration:this-is-me, subjectType=mySubjectType, subjectExpiry=2021-06-30T04:07:50Z, subjectAnnouncement=null], subjectId=integration:this-is-me],
    <any boolean>,
    false
);
-> at org.eclipse.ditto.policies.service.persistence.actors.strategies.commands.AbstractPolicyCommandStrategyTest.assertModificationResult(AbstractPolicyCommandStrategyTest.java:158)

However, there was exactly 1 interaction with this mock:
dummy.onError(
    org.eclipse.ditto.policies.model.SubjectExpiryInvalidException [message='Subject expiry timestamp '2021-06-30T04:07:50Z' is not valid.', errorCode=policies:subjectexpiry.invalid, httpStatus=HttpStatus [code=400, category=CLIENT_ERROR], description='It must not be in the past, please adjust to a timestamp in the future.', href=null, dittoHeaders=ImmutableDittoHeaders [{}]],
    ModifySubject [type=policies.commands:modifySubject, dittoHeaders=ImmutableDittoHeaders [{}], policyId=com.example:testPolicy, label=custom, subject=ImmutableSubject [subjectId=integration:this-is-me, subjectType=mySubjectType, subjectExpiry=2021-06-30T04:07:44Z, subjectAnnouncement=null]]
);
-> at org.eclipse.ditto.internal.utils.persistentactors.results.ErrorResult.accept(ErrorResult.java:44)


	at org.eclipse.ditto.policies.service.persistence.actors.strategies.commands.SubjectExpiryAdjustmentTest.doTestSubjectExpiryAdjustment(SubjectExpiryAdjustmentTest.java:181)
	at org.eclipse.ditto.policies.service.persistence.actors.strategies.commands.SubjectExpiryAdjustmentTest.roundingUpToTenSeconds(SubjectExpiryAdjustmentTest.java:70)

[ERROR] org.eclipse.ditto.policies.service.persistence.actors.strategies.commands.SubjectExpiryAdjustmentTest.roundingUpToOneMinute  Time elapsed: 0.007 s  <<< FAILURE!
org.mockito.exceptions.verification.WantedButNotInvoked: 

Wanted but not invoked:
dummy.onMutation(
    <any>,
    <Capturing argument>,
    ModifySubjectResponse [dittoHeaders=ImmutableDittoHeaders [{etag="hash:2a0abd61", response-required=false}], responseType=policies.responses:modifySubject, httpStatus=HttpStatus [code=201, category=SUCCESS], policyId=com.example:testPolicy, label=custom, subjectCreated=ImmutableSubject [subjectId=integration:this-is-me, subjectType=mySubjectType, subjectExpiry=2021-06-30T04:56:00Z, subjectAnnouncement=null], subjectId=integration:this-is-me],
    <any boolean>,
    false
);
-> at org.eclipse.ditto.policies.service.persistence.actors.strategies.commands.AbstractPolicyCommandStrategyTest.assertModificationResult(AbstractPolicyCommandStrategyTest.java:158)

However, there was exactly 1 interaction with this mock:
dummy.onError(
    org.eclipse.ditto.policies.model.SubjectExpiryInvalidException [message='Subject expiry timestamp '2021-06-30T04:56:00Z' is not valid.', errorCode=policies:subjectexpiry.invalid, httpStatus=HttpStatus [code=400, category=CLIENT_ERROR], description='It must not be in the past, please adjust to a timestamp in the future.', href=null, dittoHeaders=ImmutableDittoHeaders [{}]],
    ModifySubject [type=policies.commands:modifySubject, dittoHeaders=ImmutableDittoHeaders [{}], policyId=com.example:testPolicy, label=custom, subject=ImmutableSubject [subjectId=integration:this-is-me, subjectType=mySubjectType, subjectExpiry=2021-06-30T04:55:36.118780Z, subjectAnnouncement=null]]
);
-> at org.eclipse.ditto.internal.utils.persistentactors.results.ErrorResult.accept(ErrorResult.java:44)


	at org.eclipse.ditto.policies.service.persistence.actors.strategies.commands.SubjectExpiryAdjustmentTest.doTestSubjectExpiryAdjustment(SubjectExpiryAdjustmentTest.java:181)
	at org.eclipse.ditto.policies.service.persistence.actors.strategies.commands.SubjectExpiryAdjustmentTest.roundingUpToOneMinute(SubjectExpiryAdjustmentTest.java:85)

[ERROR] org.eclipse.ditto.policies.service.persistence.actors.strategies.commands.SubjectExpiryAdjustmentTest.roundingUpToOneSecond  Time elapsed: 0.006 s  <<< FAILURE!
org.mockito.exceptions.verification.WantedButNotInvoked: 

Wanted but not invoked:
dummy.onMutation(
    <any>,
    <Capturing argument>,
    ModifySubjectResponse [dittoHeaders=ImmutableDittoHeaders [{etag="hash:2a0ac087", response-required=false}], responseType=policies.responses:modifySubject, httpStatus=HttpStatus [code=201, category=SUCCESS], policyId=com.example:testPolicy, label=custom, subjectCreated=ImmutableSubject [subjectId=integration:this-is-me, subjectType=mySubjectType, subjectExpiry=2021-06-30T04:56:26Z, subjectAnnouncement=null], subjectId=integration:this-is-me],
    <any boolean>,
    false
);
-> at org.eclipse.ditto.policies.service.persistence.actors.strategies.commands.AbstractPolicyCommandStrategyTest.assertModificationResult(AbstractPolicyCommandStrategyTest.java:158)

However, there was exactly 1 interaction with this mock:
dummy.onError(
    org.eclipse.ditto.policies.model.SubjectExpiryInvalidException [message='Subject expiry timestamp '2021-06-30T04:56:26Z' is not valid.', errorCode=policies:subjectexpiry.invalid, httpStatus=HttpStatus [code=400, category=CLIENT_ERROR], description='It must not be in the past, please adjust to a timestamp in the future.', href=null, dittoHeaders=ImmutableDittoHeaders [{}]],
    ModifySubject [type=policies.commands:modifySubject, dittoHeaders=ImmutableDittoHeaders [{}], policyId=com.example:testPolicy, label=custom, subject=ImmutableSubject [subjectId=integration:this-is-me, subjectType=mySubjectType, subjectExpiry=2021-06-30T04:56:25.124401Z, subjectAnnouncement=null]]
);
-> at org.eclipse.ditto.internal.utils.persistentactors.results.ErrorResult.accept(ErrorResult.java:44)


	at org.eclipse.ditto.policies.service.persistence.actors.strategies.commands.SubjectExpiryAdjustmentTest.doTestSubjectExpiryAdjustment(SubjectExpiryAdjustmentTest.java:181)
	at org.eclipse.ditto.policies.service.persistence.actors.strategies.commands.SubjectExpiryAdjustmentTest.roundingUpToOneSecond(SubjectExpiryAdjustmentTest.java:54)

[ERROR] org.eclipse.ditto.policies.service.persistence.actors.strategies.commands.SubjectExpiryAdjustmentTest.doesNotRoundUpMatchingGranularity  Time elapsed: 0.006 s  <<< FAILURE!
org.mockito.exceptions.verification.WantedButNotInvoked: 

Wanted but not invoked:
dummy.onMutation(
    <any>,
    <Capturing argument>,
    ModifySubjectResponse [dittoHeaders=ImmutableDittoHeaders [{etag="hash:2a08d695", response-required=false}], responseType=policies.responses:modifySubject, httpStatus=HttpStatus [code=201, category=SUCCESS], policyId=com.example:testPolicy, label=custom, subjectCreated=ImmutableSubject [subjectId=integration:this-is-me, subjectType=mySubjectType, subjectExpiry=2021-06-30T03:49:00Z, subjectAnnouncement=null], subjectId=integration:this-is-me],
    <any boolean>,
    false
);
-> at org.eclipse.ditto.policies.service.persistence.actors.strategies.commands.AbstractPolicyCommandStrategyTest.assertModificationResult(AbstractPolicyCommandStrategyTest.java:158)

However, there was exactly 1 interaction with this mock:
dummy.onError(
    org.eclipse.ditto.policies.model.SubjectExpiryInvalidException [message='Subject expiry timestamp '2021-06-30T03:49:00Z' is not valid.', errorCode=policies:subjectexpiry.invalid, httpStatus=HttpStatus [code=400, category=CLIENT_ERROR], description='It must not be in the past, please adjust to a timestamp in the future.', href=null, dittoHeaders=ImmutableDittoHeaders [{}]],
    ModifySubject [type=policies.commands:modifySubject, dittoHeaders=ImmutableDittoHeaders [{}], policyId=com.example:testPolicy, label=custom, subject=ImmutableSubject [subjectId=integration:this-is-me, subjectType=mySubjectType, subjectExpiry=2021-06-30T03:49:00Z, subjectAnnouncement=null]]
);
-> at org.eclipse.ditto.internal.utils.persistentactors.results.ErrorResult.accept(ErrorResult.java:44)


	at org.eclipse.ditto.policies.service.persistence.actors.strategies.commands.SubjectExpiryAdjustmentTest.doTestSubjectExpiryAdjustment(SubjectExpiryAdjustmentTest.java:181)
	at org.eclipse.ditto.policies.service.persistence.actors.strategies.commands.SubjectExpiryAdjustmentTest.doesNotRoundUpMatchingGranularity(SubjectExpiryAdjustmentTest.java:155)
```

This is full log by tee
[buildinglog.txt](https://github.com/eclipse/ditto/files/6740366/buildinglog.txt)

**Comment by jack04060201** [comment]
> @jack04060201 which Java JDK are you using? There are sometimes differences when it comes to Mockito mocking in the behavior of JDKs.
> 
> When you don't need to run the tests when building Ditto, you can simply skip them:
> ```
> mvn clean install -DskipTests
> ```

Thanks for reply,
I'm using default-jdk.
Will there be any problems if I don't test him？

**Comment by thjaeckle** [comment]
> Will there be any problems if I don't test him？

Not if you didn't modify any code. 
But if you didn't modify any code, you would not require to build Ditto at all.

The build runs stable on our Jenkins environment: https://ci.eclipse.org/ditto/job/ditto-ci/

**Comment by jack04060201** [comment]
> > Will there be any problems if I don't test him？
> 
> Not if you didn't modify any code.
> But if you didn't modify any code, you would not require to build Ditto at all.

But I haven't modify any code yet. Just open dockerd and mvn clean install.
And I want to modify it too.
> 
> The build runs stable on our Jenkins environment: https://ci.eclipse.org/ditto/job/ditto-ci/

I have not used it before. I will try it.
Thank for reply.

**Comment by jack04060201** [comment]
Although it’s been a long time, I’ll update the solution,
The problem is at the time stamp.
`message='Subject expiry timestamp '2021-06-30T04:56:00Z' is not valid.', errorCode=policies:subjectexpiry.invalid, httpStatus=HttpStatus [code=400, category=CLIENT_ERROR], description='It must not be in the past, please adjust to a timestamp in the future.`
So it jumps into dummy.onError() instead of dummy.onMutation()
Because when you installing VMware, the default time zone is Los Angeles, not the local time zone, so you need to change the time zone of the VM to your local time zone. This problem may not occur on VirtualBox because you need to choose a timezone when installing OS.
