### ISSUE TITLE
oidc authentication fails with public key not found

### ISSUE THREAD

**Issue by rguikers** [eclipse/ditto#1201]
Installed ditto through the Helm chart version 2.1.0
Configured the gateway with the following oauth settings
```
global:
  jwtOnly: true
gateway:
  enableDummyAuth: false
  systemProps:
    - "-Dditto.gateway.authentication.oauth.protocol=https"
    - "-Dditto.gateway.authentication.oauth.openid-connect-issuers.myprovider.isuer=xxxxx.eu.auth0.com/"
```

As you can see, i'm using Auth0 as identity provider. The identity provider is working good, i'm testing with Insomnia, and getting a valid accesstoken

After calling an API i get the following error back as result from the call : 
```
{
  "status": 401,
  "error": "gateway:authentication.failed",
  "message": "The JWT could not be verified.",
  "description": "Public Key of issuer <https://xxxxx.eu.auth0.com/> with key ID <8oypCSjgldqkNVjDL2xZB> not found!"
}
```

the result in the gateway log : 
```
2021-10-04 19:17:55,253 WARN  [f1f62ce2-8379-40bc-aa5e-98e5fee0db9e] o.e.d.g.s.e.d.RequestTimeoutHandlingDirective  - Encountered slow HTTP request which took over <1000> ms: <1075> ms!
2021-10-04 19:18:11,985 INFO  [674d7fd5-64d0-4081-9512-f72ebebf167a] o.e.d.g.s.s.a.j.JwtAuthenticationProvider  - Completed JWT authentication successfully.
2021-10-04 19:18:11,994 INFO  [674d7fd5-64d0-4081-9512-f72ebebf167a] o.e.d.g.s.e.r.RootRouteExceptionHandler  - <GatewayAuthenticationFailedException> occurred in gateway root route: <org.eclipse.ditto.base.model.signals.commands.exceptions.GatewayAuthenticationFailedException [message='The JWT could not be verified.', errorCode=gateway:authentication.failed, httpStatus=HttpStatus [code=401, category=CLIENT_ERROR], description='Public Key of issuer <https://xxxxx.eu.auth0.com/> with key ID <8oypCSjgldqkNVjDL2xZB> not found!', href=null, dittoHeaders=ImmutableDittoHeaders [{version=2, correlation-id=674d7fd5-64d0-4081-9512-f72ebebf167a}]]>!
2021-10-04 19:18:12,039 INFO  [674d7fd5-64d0-4081-9512-f72ebebf167a] o.e.d.g.s.e.d.RequestResultLoggingDirective  - StatusCode of request GET '/api/2/search/things' was: 401
```
Seems that the gateway is unable to download the public key from the jwks_uri (i guess). but it is there (with the key given in the gateway log).

Tried everything, including debug mode logging, but no result.
I see in the gateway config file an example with Auth0, so i guess this must be working. Any help is appreciated!
Thanks,

**Comment by thjaeckle** [comment]
Hi @rguikers 

What do the DEBUG logs say? The class [DittoPublicKeyProvider](https://github.com/eclipse/ditto/blob/master/gateway/service/src/main/java/org/eclipse/ditto/gateway/service/security/authentication/jwt/DittoPublicKeyProvider.java) logs DEBUG statements for every step when retrieving and parsing the public key, e.g. this one:
https://github.com/eclipse/ditto/blob/0d3ae1a08af2999a8844b5a85c08ade11c398607/gateway/service/src/main/java/org/eclipse/ditto/gateway/service/security/authentication/jwt/DittoPublicKeyProvider.java#L174

Seems that this indeed fails.
Do you run Ditto in containers? Are those allowed to do an HTTP call to the outside world or do you have any networking policies in place?

**Comment by rguikers** [comment]
@thjaeckle 
The debug logs are not very extensive, hope i'm missing something important that leads to the issue.
When attaching to the container (pod) i can access the url for the auth0 tenant, fi, i can do a wget on the openid-configuration and get the complete json from inside the container.

```
2021-10-05 09:46:41,771 DEBUG [68ad84b4-18d5-4105-83dc-2a432296f3ab] o.e.d.g.s.e.d.CorrelationIdEnsuringDirective  - Created new correlation ID <68ad84b4-18d5-4105-83dc-2a432296f3ab>.
2021-10-05 09:46:41,773 DEBUG [] o.e.d.i.u.t.TraceUriGenerator  - Generated traceUri for '/api/2/search/things': 'TraceInformation{traceUri='/api/2/search/things/x', tags={ditto.request.path=/api/2/search/things/x}}'
2021-10-05 09:46:41,774 DEBUG [68ad84b4-18d5-4105-83dc-2a432296f3ab] o.e.d.g.s.e.d.RequestTimeoutHandlingDirective  - Started mutable timer <StartedKamonTimer [name=roundtrip_http, tags={ditto.request.path=/api/2/search/things/x, ditto.request.method=GET, segment=overall}, onStopHandlers=[org.eclipse.ditto.internal.utils.metrics.instruments.timer.PreparedKamonTimer$$Lambda$2721/0x00000000800eaba0@4d02f6a4], segments={}, startNanoTime=242362535063, startInstant=2021-10-05T07:46:41.898448001Z, stoppedTimer=null]>.
2021-10-05 09:46:41,775 DEBUG [] o.e.d.i.u.t.TraceUriGenerator  - Generated traceUri for '/api/2/search/things': 'TraceInformation{traceUri='/api/2/search/things/x', tags={ditto.request.path=/api/2/search/things/x}}'
2021-10-05 09:46:41,795 DEBUG [] o.e.d.g.s.s.a.j.DittoPublicKeyProvider  - Loading public key with id <8oypCSjgldqkNVjDL2xZB> from issuer <https://xxxxx.eu.auth0.com/>.
2021-10-05 09:46:41,806 DEBUG [68ad84b4-18d5-4105-83dc-2a432296f3ab] o.e.d.g.s.s.a.j.JwtAuthenticationProvider  - The JWT is invalid.
org.eclipse.ditto.base.model.signals.commands.exceptions.GatewayAuthenticationFailedException: Public Key of issuer <https://xxxxx.eu.auth0.com/> with key ID <8oypCSjgldqkWVjDL2xZB> not found!
	at org.eclipse.ditto.base.model.signals.commands.exceptions.GatewayAuthenticationFailedException$Builder.doBuild(GatewayAuthenticationFailedException.java:124)
	at org.eclipse.ditto.base.model.signals.commands.exceptions.GatewayAuthenticationFailedException$Builder.doBuild(GatewayAuthenticationFailedException.java:106)
	at org.eclipse.ditto.base.model.exceptions.DittoRuntimeExceptionBuilder.build(DittoRuntimeExceptionBuilder.java:176)
	at org.eclipse.ditto.gateway.service.security.authentication.jwt.DefaultJwtValidator.lambda$validate$1(DefaultJwtValidator.java:69)
	at org.eclipse.ditto.gateway.service.security.authentication.jwt.DefaultJwtValidator$$Lambda$3111/0x00000000702ac600.get(Unknown Source)
	at java.base/java.util.Optional.orElseGet(Optional.java:369)
	at org.eclipse.ditto.gateway.service.security.authentication.jwt.DefaultJwtValidator.lambda$validate$2(DefaultJwtValidator.java:66)
	at org.eclipse.ditto.gateway.service.security.authentication.jwt.DefaultJwtValidator$$Lambda$3109/0x0000000070179730.apply(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:680)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:658)
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2094)
	at org.eclipse.ditto.gateway.service.security.authentication.jwt.DefaultJwtValidator.validate(DefaultJwtValidator.java:64)
	at org.eclipse.ditto.gateway.service.security.authentication.jwt.JwtAuthenticationProvider.getAuthenticationResult(JwtAuthenticationProvider.java:135)
	at org.eclipse.ditto.gateway.service.security.authentication.jwt.JwtAuthenticationProvider.tryToAuthenticate(JwtAuthenticationProvider.java:125)
	at org.eclipse.ditto.gateway.service.security.authentication.TimeMeasuringAuthenticationProvider.authenticate(TimeMeasuringAuthenticationProvider.java:66)
	at org.eclipse.ditto.gateway.service.security.authentication.AuthenticationChain$AuthResultAccumulator.andThen(AuthenticationChain.java:190)
	at org.eclipse.ditto.gateway.service.security.authentication.AuthenticationChain.lambda$authenticate$0(AuthenticationChain.java:98)
	at org.eclipse.ditto.gateway.service.security.authentication.AuthenticationChain$$Lambda$3088/0x000000007c0eb1a0.apply(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:866)
2021-10-05 09:46:41,809 INFO  [68ad84b4-18d5-4105-83dc-2a432296f3ab] o.e.d.g.s.s.a.j.JwtAuthenticationProvider  - Completed JWT authentication successfully.
2021-10-05 09:46:41,814 DEBUG [68ad84b4-18d5-4105-83dc-2a432296f3ab] o.e.d.g.s.s.a.AuthenticationChain  - Authentication using authentication provider <JwtAuthenticationProvider> to URI <http://dev.localtest.me/api/2/search/things> failed due to GatewayAuthenticationFailedException: The JWT could not be verified.
2021-10-05 09:46:41,819 DEBUG [] o.e.d.g.s.e.d.a.GatewayAuthenticationDirective  - Authentication for URI <http://dev.localtest.me/api/2/search/things> failed. Rethrow DittoRuntimeException.
org.eclipse.ditto.base.model.signals.commands.exceptions.GatewayAuthenticationFailedException: The JWT could not be verified.
	at org.eclipse.ditto.base.model.signals.commands.exceptions.GatewayAuthenticationFailedException$Builder.doBuild(GatewayAuthenticationFailedException.java:124)
	at org.eclipse.ditto.base.model.signals.commands.exceptions.GatewayAuthenticationFailedException$Builder.doBuild(GatewayAuthenticationFailedException.java:106)
	at org.eclipse.ditto.base.model.exceptions.DittoRuntimeExceptionBuilder.build(DittoRuntimeExceptionBuilder.java:176)
	at org.eclipse.ditto.gateway.service.security.authentication.jwt.JwtAuthenticationProvider.buildJwtUnauthorizedException(JwtAuthenticationProvider.java:161)
	at org.eclipse.ditto.gateway.service.security.authentication.jwt.JwtAuthenticationProvider.lambda$getAuthenticationResult$1(JwtAuthenticationProvider.java:141)
	at org.eclipse.ditto.gateway.service.security.authentication.jwt.JwtAuthenticationProvider$$Lambda$3112/0x000000007021d380.apply(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1106)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2235)
	at org.eclipse.ditto.gateway.service.security.authentication.jwt.JwtAuthenticationProvider.getAuthenticationResult(JwtAuthenticationProvider.java:136)
	at org.eclipse.ditto.gateway.service.security.authentication.jwt.JwtAuthenticationProvider.tryToAuthenticate(JwtAuthenticationProvider.java:125)
	at org.eclipse.ditto.gateway.service.security.authentication.TimeMeasuringAuthenticationProvider.authenticate(TimeMeasuringAuthenticationProvider.java:66)
	at org.eclipse.ditto.gateway.service.security.authentication.AuthenticationChain$AuthResultAccumulator.andThen(AuthenticationChain.java:190)
	at org.eclipse.ditto.gateway.service.security.authentication.AuthenticationChain.lambda$authenticate$0(AuthenticationChain.java:98)
	at org.eclipse.ditto.gateway.service.security.authentication.AuthenticationChain$$Lambda$3088/0x000000007c0eb1a0.apply(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:866)
Caused by: org.eclipse.ditto.base.model.signals.commands.exceptions.GatewayAuthenticationFailedException: Public Key of issuer <https://xxxxx.auth0.com/> with key ID <8oypCSjgldqkWVjDL2xZB> not found!
	at org.eclipse.ditto.base.model.signals.commands.exceptions.GatewayAuthenticationFailedException$Builder.doBuild(GatewayAuthenticationFailedException.java:124)
	at org.eclipse.ditto.base.model.signals.commands.exceptions.GatewayAuthenticationFailedException$Builder.doBuild(GatewayAuthenticationFailedException.java:106)
	at org.eclipse.ditto.base.model.exceptions.DittoRuntimeExceptionBuilder.build(DittoRuntimeExceptionBuilder.java:176)
	at org.eclipse.ditto.gateway.service.security.authentication.jwt.DefaultJwtValidator.lambda$validate$1(DefaultJwtValidator.java:69)
	at org.eclipse.ditto.gateway.service.security.authentication.jwt.DefaultJwtValidator$$Lambda$3111/0x00000000702ac600.get(Unknown Source)
	at java.base/java.util.Optional.orElseGet(Optional.java:369)
	at org.eclipse.ditto.gateway.service.security.authentication.jwt.DefaultJwtValidator.lambda$validate$2(DefaultJwtValidator.java:66)
	at org.eclipse.ditto.gateway.service.security.authentication.jwt.DefaultJwtValidator$$Lambda$3109/0x0000000070179730.apply(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:680)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:658)
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2094)
	at org.eclipse.ditto.gateway.service.security.authentication.jwt.DefaultJwtValidator.validate(DefaultJwtValidator.java:64)
	at org.eclipse.ditto.gateway.service.security.authentication.jwt.JwtAuthenticationProvider.getAuthenticationResult(JwtAuthenticationProvider.java:135)
	... 11 common frames omitted
2021-10-05 09:46:41,823 INFO  [68ad84b4-18d5-4105-83dc-2a432296f3ab] o.e.d.g.s.e.r.RootRouteExceptionHandler  - <GatewayAuthenticationFailedException> occurred in gateway root route: <org.eclipse.ditto.base.model.signals.commands.exceptions.GatewayAuthenticationFailedException [message='The JWT could not be verified.', errorCode=gateway:authentication.failed, httpStatus=HttpStatus [code=401, category=CLIENT_ERROR], description='Public Key of issuer <https://xxxxx.auth0.com/> with key ID <8oypCSjgldqkWVjDL2xZB> not found!', href=null, dittoHeaders=ImmutableDittoHeaders [{version=2, correlation-id=68ad84b4-18d5-4105-83dc-2a432296f3ab}]]>!
2021-10-05 09:46:41,832 INFO  [68ad84b4-18d5-4105-83dc-2a432296f3ab] o.e.d.g.s.e.d.RequestResultLoggingDirective  - StatusCode of request GET '/api/2/search/things' was: 401
2021-10-05 09:46:41,832 DEBUG [68ad84b4-18d5-4105-83dc-2a432296f3ab] o.e.d.g.s.e.d.RequestResultLoggingDirective  - Raw request URI was: Raw-Request-URI: /api/2/search/things
2021-10-05 09:46:41,833 DEBUG [68ad84b4-18d5-4105-83dc-2a432296f3ab] o.e.d.g.s.e.d.RequestTimeoutHandlingDirective  - Finished timer <StartedKamonTimer [name=roundtrip_http, tags={ditto.request.path=/api/2/search/things/x, ditto.statusCode=401, ditto.request.method=GET, segment=overall}, onStopHandlers=[org.eclipse.ditto.internal.utils.metrics.instruments.timer.PreparedKamonTimer$$Lambda$2721/0x00000000800eaba0@4d02f6a4], segments={}, startNanoTime=242362535063, startInstant=2021-10-05T07:46:41.898448001Z, stoppedTimer=StoppedKamonTimer [name=roundtrip_http, tags={ditto.request.path=/api/2/search/things/x, ditto.statusCode=401, ditto.request.method=GET, segment=overall}, startNanoTime=242362535063, endNanoTime=242421446934]]> with status <401>.

```

**Comment by thjaeckle** [comment]
@rguikers I fear that this could be indeed a bug, as I am missing the mentioned DEBUG log-statement I mentioned above: `Loading public keys from discovery endpoint <...>`.

The most likely possibility is that the exception here is thrown and silently dropped (by the cache loader which invoked the method):
https://github.com/eclipse/ditto/blob/0d3ae1a08af2999a8844b5a85c08ade11c398607/gateway/service/src/main/java/org/eclipse/ditto/gateway/service/security/authentication/jwt/DittoPublicKeyProvider.java#L136

I think that this most likely is related to the Ditto helm chart.
Maybe some quotes are missing around the "args", I just rendered the k8s template and got the following output:
```
...
      containers:
        - name: ditto-gateway
          image: docker.io/eclipse/ditto-gateway:2.1.0
          imagePullPolicy: IfNotPresent
          args:
            - "java"
            - -Dditto.gateway.authentication.oauth.protocol=https
            - -Dditto.gateway.authentication.oauth.openid-connect-issuers.myprovider.isuer=xxxxx.eu.auth0.com/
            - "-jar"
            - "/opt/ditto/starter.jar"
          env:
            - name: DITTO_LOGGING_FILE_APPENDER
              value: "false"
...
```

Will have to check, but I think that the args should be in quotes.

**Comment by thjaeckle** [comment]
The quotation will be fixed by eclipse/packages#297 - however I am not 100% confident this will fix this issue.

**Comment by rguikers** [comment]
@thjaeckle , thanks for this nice find!, i will check with my system with the fix you made..

**Comment by rguikers** [comment]
Sorry to say that this did not fix the issue. In fact, it is possible to use it without quotes (although not as specific ), The resulting command on my side is still as it should be :
```
java -Dditto.gateway.authentication.oauth.protocol=https -Dditto.gateway.authentication.oauth.openid-connect-issuers.myprovider.isuer=xxxxx.eu.auth0.com/ -jar /opt/ditto/starter.jar
```

**Comment by thjaeckle** [comment]
Then I am out of ideas solving this without debugging, sorry.
The trailing slash at the issuer URL looks a little suspicious to me, but when this also occurs in the JWT, this should work. 

Does Auth0 provide a free plan for evaluation?

**Comment by rguikers** [comment]
Yes, there is a free plan on Auth0 (https://auth0.com/). BTW, i also tried a docker-compose setup, and this leads to the same error.

**Comment by thjaeckle** [comment]
@rguikers 
After debugging with your parameters I could reproduce - until I noticed a typo :D
You wrote:
```
-Dditto.gateway.authentication.oauth.openid-connect-issuers.myprovider.isuer
```
Correct would be:
```
-Dditto.gateway.authentication.oauth.openid-connect-issuers.myprovider.issuer
```

Please adjust and provide feedback if that solves your problem :)

**Comment by rguikers** [comment]
@thjaeckle , Oh man, this is indeed a stupid mistake. Sorry to have wasted your time on this
But to my defense, still strange that the system is still interpreting the url and the log prints the message related to the url :)

```
{
  "status": 401,
  "error": "gateway:authentication.failed",
  "message": "The JWT could not be verified.",
  "description": "Public Key of issuer <https://xxxxx.eu.auth0.com/> with key ID <8oypCSjgldqkNVjDL2xZB> not found!"
}
```

Thanks Thomas!

**Comment by thjaeckle** [comment]
the url is extracted from the token, so this is confusing indeed.
Will improve logging at this place..
