### ISSUE TITLE
Docker compose up failure

### ISSUE THREAD

**Issue by RaiBnod** [eclipse/ditto#249]
I have gone through the README.md file and when I hit the command for 'docker-compose up -d', it should work fine. But I got errors having following stdout output:

```
things-search_1  | 2018-10-03 20:03:49,890 ERROR [] o.e.d.s.t.s.SearchService  - An exception occurred in main method of <org.eclipse.ditto.services.thingsearch.starter.SearchService>!
things-search_1  | java.util.concurrent.TimeoutException: Futures timed out after [10000 milliseconds]
things-search_1  | 	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:255)
things-search_1  | 	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:259)
things-search_1  | 	at scala.concurrent.Await$.$anonfun$result$1(package.scala:215)
things-search_1  | 	at scala.concurrent.Await$$$Lambda$311.000000008CDC7710.apply(Unknown Source)
things-search_1  | 	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
things-search_1  | 	at scala.concurrent.Await$.result(package.scala:142)
things-search_1  | 	at akka.remote.Remoting.start(Remoting.scala:194)
things-search_1  | 	at akka.remote.RemoteActorRefProvider.init(RemoteActorRefProvider.scala:222)
things-search_1  | 	at akka.cluster.ClusterActorRefProvider.init(ClusterActorRefProvider.scala:32)
things-search_1  | 	at akka.actor.ActorSystemImpl.liftedTree2$1(ActorSystem.scala:826)
things-search_1  | 	at akka.actor.ActorSystemImpl._start$lzycompute(ActorSystem.scala:823)
things-search_1  | 	at akka.actor.ActorSystemImpl._start(ActorSystem.scala:823)
things-search_1  | 	at akka.actor.ActorSystemImpl.start(ActorSystem.scala:842)
things-search_1  | 	at akka.actor.ActorSystem$.apply(ActorSystem.scala:246)
things-search_1  | 	at akka.actor.ActorSystem$.apply(ActorSystem.scala:289)
things-search_1  | 	at akka.actor.ActorSystem$.apply(ActorSystem.scala:264)
things-search_1  | 	at akka.actor.ActorSystem$.create(ActorSystem.scala:192)
things-search_1  | 	at akka.actor.ActorSystem.create(ActorSystem.scala)
things-search_1  | 	at org.eclipse.ditto.services.base.DittoService.createActorSystem(DittoService.java:275)
things-search_1  | 	at org.eclipse.ditto.services.base.DittoService.doStart(DittoService.java:150)
things-search_1  | 	at org.eclipse.ditto.services.base.DittoService$$Lambda$11.000000008C81C240.call(Unknown Source)
things-search_1  | 	at org.eclipse.ditto.services.base.MainMethodExceptionHandler.tryToRunMainMethodBody(MainMethodExceptionHandler.java:68)
things-search_1  | 	at org.eclipse.ditto.services.base.MainMethodExceptionHandler.call(MainMethodExceptionHandler.java:62)
things-search_1  | 	at org.eclipse.ditto.services.base.DittoService.start(DittoService.java:134)
things-search_1  | 	at org.eclipse.ditto.services.thingsearch.starter.SearchService.main(SearchService.java:39)
things-search_1  | 2018-10-03 20:03:49,890 ERROR [] o.e.d.s.t.s.SearchService  - An exception occurred in main method of <org.eclipse.ditto.services.thingsearch.starter.SearchService>!
things-search_1  | java.util.concurrent.TimeoutException: Futures timed out after [10000 milliseconds]
things-search_1  | 	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:255)
things-search_1  | 	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:259)
things-search_1  | 	at scala.concurrent.Await$.$anonfun$result$1(package.scala:215)
things-search_1  | 	at scala.concurrent.Await$$$Lambda$311.000000008CDC7710.apply(Unknown Source)
things-search_1  | 	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
things-search_1  | 	at scala.concurrent.Await$.result(package.scala:142)
things-search_1  | 	at akka.remote.Remoting.start(Remoting.scala:194)
things-search_1  | 	at akka.remote.RemoteActorRefProvider.init(RemoteActorRefProvider.scala:222)
things-search_1  | 	at akka.cluster.ClusterActorRefProvider.init(ClusterActorRefProvider.scala:32)
things-search_1  | 	at akka.actor.ActorSystemImpl.liftedTree2$1(ActorSystem.scala:826)
things-search_1  | 	at akka.actor.ActorSystemImpl._start$lzycompute(ActorSystem.scala:823)
things-search_1  | 	at akka.actor.ActorSystemImpl._start(ActorSystem.scala:823)
things-search_1  | 	at akka.actor.ActorSystemImpl.start(ActorSystem.scala:842)
things-search_1  | 	at akka.actor.ActorSystem$.apply(ActorSystem.scala:246)
things-search_1  | 	at akka.actor.ActorSystem$.apply(ActorSystem.scala:289)
things-search_1  | 	at akka.actor.ActorSystem$.apply(ActorSystem.scala:264)
things-search_1  | 	at akka.actor.ActorSystem$.create(ActorSystem.scala:192)
things-search_1  | 	at akka.actor.ActorSystem.create(ActorSystem.scala)
things-search_1  | 	at org.eclipse.ditto.services.base.DittoService.createActorSystem(DittoService.java:275)
things-search_1  | 	at org.eclipse.ditto.services.base.DittoService.doStart(DittoService.java:150)
things-search_1  | 	at org.eclipse.ditto.services.base.DittoService$$Lambda$11.000000008C81C240.call(Unknown Source)
things-search_1  | 	at org.eclipse.ditto.services.base.MainMethodExceptionHandler.tryToRunMainMethodBody(MainMethodExceptionHandler.java:68)
things-search_1  | 	at org.eclipse.ditto.services.base.MainMethodExceptionHandler.call(MainMethodExceptionHandler.java:62)
things-search_1  | 	at org.eclipse.ditto.services.base.DittoService.start(DittoService.java:134)
things-search_1  | 	at org.eclipse.ditto.services.thingsearch.starter.SearchService.main(SearchService.java:39)
things-search_1  | Exception in thread "main" java.lang.RuntimeException: Exception on main thread: Futures timed out after [10000 milliseconds]
things-search_1  | 	at org.eclipse.ditto.services.base.MainMethodExceptionHandler.tryToRunMainMethodBody(MainMethodExceptionHandler.java:75)
things-search_1  | 	at org.eclipse.ditto.services.base.MainMethodExceptionHandler.call(MainMethodExceptionHandler.java:62)
things-search_1  | 	at org.eclipse.ditto.services.base.DittoService.start(DittoService.java:134)
things-search_1  | 	at org.eclipse.ditto.services.thingsearch.starter.SearchService.main(SearchService.java:39)
things-search_1  | Caused by: java.util.concurrent.TimeoutException: Futures timed out after [10000 milliseconds]
things-search_1  | 	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:255)
things-search_1  | 	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:259)
things-search_1  | 	at scala.concurrent.Await$.$anonfun$result$1(package.scala:215)
things-search_1  | 	at scala.concurrent.Await$$$Lambda$311.000000008CDC7710.apply(Unknown Source)
things-search_1  | 	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
things-search_1  | 	at scala.concurrent.Await$.result(package.scala:142)
things-search_1  | 	at akka.remote.Remoting.start(Remoting.scala:194)
things-search_1  | 	at akka.remote.RemoteActorRefProvider.init(RemoteActorRefProvider.scala:222)
things-search_1  | 	at akka.cluster.ClusterActorRefProvider.init(ClusterActorRefProvider.scala:32)
things-search_1  | 	at akka.actor.ActorSystemImpl.liftedTree2$1(ActorSystem.scala:826)
things-search_1  | 	at akka.actor.ActorSystemImpl._start$lzycompute(ActorSystem.scala:823)
things-search_1  | 	at akka.actor.ActorSystemImpl._start(ActorSystem.scala:823)
things-search_1  | 	at akka.actor.ActorSystemImpl.start(ActorSystem.scala:842)
things-search_1  | 	at akka.actor.ActorSystem$.apply(ActorSystem.scala:246)
things-search_1  | 	at akka.actor.ActorSystem$.apply(ActorSystem.scala:289)
things-search_1  | 	at akka.actor.ActorSystem$.apply(ActorSystem.scala:264)
things-search_1  | 	at akka.actor.ActorSystem$.create(ActorSystem.scala:192)
things-search_1  | 	at akka.actor.ActorSystem.create(ActorSystem.scala)
things-search_1  | 	at org.eclipse.ditto.services.base.DittoService.createActorSystem(DittoService.java:275)
things-search_1  | 	at org.eclipse.ditto.services.base.DittoService.doStart(DittoService.java:150)
things-search_1  | 	at org.eclipse.ditto.services.base.DittoService$$Lambda$11.000000008C81C240.call(Unknown Source)
things-search_1  | 	at org.eclipse.ditto.services.base.MainMethodExceptionHandler.tryToRunMainMethodBody(MainMethodExceptionHandler.java:68)
things-search_1  | 	... 3 more
concierge_1      | 2018-10-03 20:03:50,618 INFO  [] a.r.RemoteActorRefProvider$RemotingTerminator akka://ditto-cluster/system/remoting-terminator - Shutting down remote daemon.
concierge_1      | 2018-10-03 20:03:50,883 INFO  [] a.r.RemoteActorRefProvider$RemotingTerminator akka://ditto-cluster/system/remoting-terminator - Remote daemon shut down; proceeding with flushing remote transports.
concierge_1      | 2018-10-03 20:03:51,029 ERROR [] akka.remote.Remoting akka.remote.Remoting - Remoting system has been terminated abrubtly. Attempting to shut down transports
concierge_1      | 2018-10-03 20:03:51,029 ERROR [] akka.remote.Remoting akka.remote.Remoting - Remoting system has been terminated abrubtly. Attempting to shut down transports
concierge_1      | 2018-10-03 20:03:51,143 INFO  [] akka.remote.Remoting akka.remote.Remoting - Remoting shut down
things-search_1  | 2018-10-03 20:03:51,410 INFO  [] a.r.RemoteActorRefProvider$RemotingTerminator akka://ditto-cluster/system/remoting-terminator - Shutting down remote daemon.
concierge_1      | 2018-10-03 20:03:51,806 INFO  [] a.r.RemoteActorRefProvider$RemotingTerminator akka://ditto-cluster/system/remoting-terminator - Remoting shut down.
things-search_1  | 2018-10-03 20:03:51,891 INFO  [] a.r.RemoteActorRefProvider$RemotingTerminator akka://ditto-cluster/system/remoting-terminator - Remote daemon shut down; proceeding with flushing remote transports.
things-search_1  | 2018-10-03 20:03:52,022 INFO  [] akka.remote.Remoting akka.remote.Remoting - Remoting shut down
things-search_1  | 2018-10-03 20:03:52,183 ERROR [] akka.remote.Remoting akka.remote.Remoting - Remoting system has been terminated abrubtly. Attempting to shut down transports
things-search_1  | 2018-10-03 20:03:52,183 ERROR [] akka.remote.Remoting akka.remote.Remoting - Remoting system has been terminated abrubtly. Attempting to shut down transports
things-search_1  | 2018-10-03 20:03:52,342 INFO  [] a.r.RemoteActorRefProvider$RemotingTerminator akka://ditto-cluster/system/remoting-terminator - Remoting shut down.
connectivity_1   | 2018-10-03 20:03:55,892 ERROR [] akka.remote.Remoting akka.remote.Remoting - Remoting error: [Startup timed out. This is usually related to actor system host setting or host name resolution misconfiguration.] [
connectivity_1   | akka.remote.RemoteTransportException: Startup timed out. This is usually related to actor system host setting or host name resolution misconfiguration.
connectivity_1   | 	at akka.remote.Remoting.akka$remote$Remoting$$notifyError(Remoting.scala:148)
connectivity_1   | 	at akka.remote.Remoting.start(Remoting.scala:211)
connectivity_1   | 	at akka.remote.RemoteActorRefProvider.init(RemoteActorRefProvider.scala:222)
connectivity_1   | 	at akka.cluster.ClusterActorRefProvider.init(ClusterActorRefProvider.scala:32)
connectivity_1   | 	at akka.actor.ActorSystemImpl.liftedTree2$1(ActorSystem.scala:826)
connectivity_1   | 	at akka.actor.ActorSystemImpl._start$lzycompute(ActorSystem.scala:823)
connectivity_1   | 	at akka.actor.ActorSystemImpl._start(ActorSystem.scala:823)
connectivity_1   | 	at akka.actor.ActorSystemImpl.start(ActorSystem.scala:842)
connectivity_1   | 	at akka.actor.ActorSystem$.apply(ActorSystem.scala:246)
connectivity_1   | 	at akka.actor.ActorSystem$.apply(ActorSystem.scala:289)
connectivity_1   | 	at akka.actor.ActorSystem$.apply(ActorSystem.scala:264)
connectivity_1   | 	at akka.actor.ActorSystem$.create(ActorSystem.scala:192)
connectivity_1   | 	at akka.actor.ActorSystem.create(ActorSystem.scala)
connectivity_1   | 	at org.eclipse.ditto.services.base.DittoService.createActorSystem(DittoService.java:275)
connectivity_1   | 	at org.eclipse.ditto.services.base.DittoService.doStart(DittoService.java:150)
connectivity_1   | 	at org.eclipse.ditto.services.base.DittoService$$Lambda$11.00000000A8812F00.call(Unknown Source)
connectivity_1   | 	at org.eclipse.ditto.services.base.MainMethodExceptionHandler.tryToRunMainMethodBody(MainMethodExceptionHandler.java:68)
connectivity_1   | 	at org.eclipse.ditto.services.base.MainMethodExceptionHandler.call(MainMethodExceptionHandler.java:62)
connectivity_1   | 	at org.eclipse.ditto.services.base.DittoService.start(DittoService.java:134)
connectivity_1   | 	at org.eclipse.ditto.services.connectivity.ConnectivityService.main(ConnectivityService.java:55)
connectivity_1   | Caused by: java.util.concurrent.TimeoutException: Futures timed out after [10000 milliseconds]
connectivity_1   | 	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:255)
connectivity_1   | 	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:259)
connectivity_1   | 	at scala.concurrent.Await$.$anonfun$result$1(package.scala:215)
connectivity_1   | 	at scala.concurrent.Await$$$Lambda$312.00000000A8DE0B10.apply(Unknown Source)
connectivity_1   | 	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
connectivity_1   | 	at scala.concurrent.Await$.result(package.scala:142)
connectivity_1   | 	at akka.remote.Remoting.start(Remoting.scala:194)
connectivity_1   | 	... 18 more
connectivity_1   | ]
connectivity_1   | 2018-10-03 20:03:55,892 ERROR [] akka.remote.Remoting akka.remote.Remoting - Remoting error: [Startup timed out. This is usually related to actor system host setting or host name resolution misconfiguration.] [
connectivity_1   | akka.remote.RemoteTransportException: Startup timed out. This is usually related to actor system host setting or host name resolution misconfiguration.
connectivity_1   | 	at akka.remote.Remoting.akka$remote$Remoting$$notifyError(Remoting.scala:148)
connectivity_1   | 	at akka.remote.Remoting.start(Remoting.scala:211)
connectivity_1   | 	at akka.remote.RemoteActorRefProvider.init(RemoteActorRefProvider.scala:222)
connectivity_1   | 	at akka.cluster.ClusterActorRefProvider.init(ClusterActorRefProvider.scala:32)
connectivity_1   | 	at akka.actor.ActorSystemImpl.liftedTree2$1(ActorSystem.scala:826)
connectivity_1   | 	at akka.actor.ActorSystemImpl._start$lzycompute(ActorSystem.scala:823)
connectivity_1   | 	at akka.actor.ActorSystemImpl._start(ActorSystem.scala:823)
connectivity_1   | 	at akka.actor.ActorSystemImpl.start(ActorSystem.scala:842)
connectivity_1   | 	at akka.actor.ActorSystem$.apply(ActorSystem.scala:246)
connectivity_1   | 	at akka.actor.ActorSystem$.apply(ActorSystem.scala:289)
connectivity_1   | 	at akka.actor.ActorSystem$.apply(ActorSystem.scala:264)
connectivity_1   | 	at akka.actor.ActorSystem$.create(ActorSystem.scala:192)
connectivity_1   | 	at akka.actor.ActorSystem.create(ActorSystem.scala)
connectivity_1   | 	at org.eclipse.ditto.services.base.DittoService.createActorSystem(DittoService.java:275)
connectivity_1   | 	at org.eclipse.ditto.services.base.DittoService.doStart(DittoService.java:150)
connectivity_1   | 	at org.eclipse.ditto.services.base.DittoService$$Lambda$11.00000000A8812F00.call(Unknown Source)
connectivity_1   | 	at org.eclipse.ditto.services.base.MainMethodExceptionHandler.tryToRunMainMethodBody(MainMethodExceptionHandler.java:68)
connectivity_1   | 	at org.eclipse.ditto.services.base.MainMethodExceptionHandler.call(MainMethodExceptionHandler.java:62)
connectivity_1   | 	at org.eclipse.ditto.services.base.DittoService.start(DittoService.java:134)
connectivity_1   | 	at org.eclipse.ditto.services.connectivity.ConnectivityService.main(ConnectivityService.java:55)
connectivity_1   | Caused by: java.util.concurrent.TimeoutException: Futures timed out after [10000 milliseconds]
connectivity_1   | 	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:255)
connectivity_1   | 	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:259)
connectivity_1   | 	at scala.concurrent.Await$.$anonfun$result$1(package.scala:215)
connectivity_1   | 	at scala.concurrent.Await$$$Lambda$312.00000000A8DE0B10.apply(Unknown Source)
connectivity_1   | 	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
connectivity_1   | 	at scala.concurrent.Await$.result(package.scala:142)
connectivity_1   | 	at akka.remote.Remoting.start(Remoting.scala:194)
connectivity_1   | 	... 18 more
connectivity_1   | ]
connectivity_1   | 2018-10-03 20:03:56,042 ERROR [] o.e.d.s.c.ConnectivityService  - An exception occurred in main method of <org.eclipse.ditto.services.connectivity.ConnectivityService>!
connectivity_1   | java.util.concurrent.TimeoutException: Futures timed out after [10000 milliseconds]
connectivity_1   | 	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:255)
connectivity_1   | 	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:259)
connectivity_1   | 	at scala.concurrent.Await$.$anonfun$result$1(package.scala:215)
connectivity_1   | 	at scala.concurrent.Await$$$Lambda$312.00000000A8DE0B10.apply(Unknown Source)
connectivity_1   | 	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
connectivity_1   | 	at scala.concurrent.Await$.result(package.scala:142)
connectivity_1   | 	at akka.remote.Remoting.start(Remoting.scala:194)
connectivity_1   | 	at akka.remote.RemoteActorRefProvider.init(RemoteActorRefProvider.scala:222)
connectivity_1   | 	at akka.cluster.ClusterActorRefProvider.init(ClusterActorRefProvider.scala:32)
connectivity_1   | 	at akka.actor.ActorSystemImpl.liftedTree2$1(ActorSystem.scala:826)
connectivity_1   | 	at akka.actor.ActorSystemImpl._start$lzycompute(ActorSystem.scala:823)
connectivity_1   | 	at akka.actor.ActorSystemImpl._start(ActorSystem.scala:823)
connectivity_1   | 	at akka.actor.ActorSystemImpl.start(ActorSystem.scala:842)
connectivity_1   | 	at akka.actor.ActorSystem$.apply(ActorSystem.scala:246)
connectivity_1   | 	at akka.actor.ActorSystem$.apply(ActorSystem.scala:289)
connectivity_1   | 	at akka.actor.ActorSystem$.apply(ActorSystem.scala:264)
connectivity_1   | 	at akka.actor.ActorSystem$.create(ActorSystem.scala:192)
connectivity_1   | 	at akka.actor.ActorSystem.create(ActorSystem.scala)
connectivity_1   | 	at org.eclipse.ditto.services.base.DittoService.createActorSystem(DittoService.java:275)
connectivity_1   | 	at org.eclipse.ditto.services.base.DittoService.doStart(DittoService.java:150)
connectivity_1   | 	at org.eclipse.ditto.services.base.DittoService$$Lambda$11.00000000A8812F00.call(Unknown Source)
connectivity_1   | 	at org.eclipse.ditto.services.base.MainMethodExceptionHandler.tryToRunMainMethodBody(MainMethodExceptionHandler.java:68)
connectivity_1   | 	at org.eclipse.ditto.services.base.MainMethodExceptionHandler.call(MainMethodExceptionHandler.java:62)
connectivity_1   | 	at org.eclipse.ditto.services.base.DittoService.start(DittoService.java:134)
connectivity_1   | 	at org.eclipse.ditto.services.connectivity.ConnectivityService.main(ConnectivityService.java:55)
connectivity_1   | 2018-10-03 20:03:56,042 ERROR [] o.e.d.s.c.ConnectivityService  - An exception occurred in main method of <org.eclipse.ditto.services.connectivity.ConnectivityService>!
connectivity_1   | java.util.concurrent.TimeoutException: Futures timed out after [10000 milliseconds]
connectivity_1   | 	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:255)
connectivity_1   | 	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:259)
connectivity_1   | 	at scala.concurrent.Await$.$anonfun$result$1(package.scala:215)
connectivity_1   | 	at scala.concurrent.Await$$$Lambda$312.00000000A8DE0B10.apply(Unknown Source)
connectivity_1   | 	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
connectivity_1   | 	at scala.concurrent.Await$.result(package.scala:142)
connectivity_1   | 	at akka.remote.Remoting.start(Remoting.scala:194)
connectivity_1   | 	at akka.remote.RemoteActorRefProvider.init(RemoteActorRefProvider.scala:222)
connectivity_1   | 	at akka.cluster.ClusterActorRefProvider.init(ClusterActorRefProvider.scala:32)
connectivity_1   | 	at akka.actor.ActorSystemImpl.liftedTree2$1(ActorSystem.scala:826)
connectivity_1   | 	at akka.actor.ActorSystemImpl._start$lzycompute(ActorSystem.scala:823)
connectivity_1   | 	at akka.actor.ActorSystemImpl._start(ActorSystem.scala:823)
connectivity_1   | 	at akka.actor.ActorSystemImpl.start(ActorSystem.scala:842)
connectivity_1   | 	at akka.actor.ActorSystem$.apply(ActorSystem.scala:246)
connectivity_1   | 	at akka.actor.ActorSystem$.apply(ActorSystem.scala:289)
connectivity_1   | 	at akka.actor.ActorSystem$.apply(ActorSystem.scala:264)
connectivity_1   | 	at akka.actor.ActorSystem$.create(ActorSystem.scala:192)
connectivity_1   | 	at akka.actor.ActorSystem.create(ActorSystem.scala)
connectivity_1   | 	at org.eclipse.ditto.services.base.DittoService.createActorSystem(DittoService.java:275)
connectivity_1   | 	at org.eclipse.ditto.services.base.DittoService.doStart(DittoService.java:150)
connectivity_1   | 	at org.eclipse.ditto.services.base.DittoService$$Lambda$11.00000000A8812F00.call(Unknown Source)
connectivity_1   | 	at org.eclipse.ditto.services.base.MainMethodExceptionHandler.tryToRunMainMethodBody(MainMethodExceptionHandler.java:68)
connectivity_1   | 	at org.eclipse.ditto.services.base.MainMethodExceptionHandler.call(MainMethodExceptionHandler.java:62)
connectivity_1   | 	at org.eclipse.ditto.services.base.DittoService.start(DittoService.java:134)
connectivity_1   | 	at org.eclipse.ditto.services.connectivity.ConnectivityService.main(ConnectivityService.java:55)
connectivity_1   | Exception in thread "main" java.lang.RuntimeException: Exception on main thread: Futures timed out after [10000 milliseconds]
connectivity_1   | 	at org.eclipse.ditto.services.base.MainMethodExceptionHandler.tryToRunMainMethodBody(MainMethodExceptionHandler.java:75)
connectivity_1   | 	at org.eclipse.ditto.services.base.MainMethodExceptionHandler.call(MainMethodExceptionHandler.java:62)
connectivity_1   | 	at org.eclipse.ditto.services.base.DittoService.start(DittoService.java:134)
connectivity_1   | 	at org.eclipse.ditto.services.connectivity.ConnectivityService.main(ConnectivityService.java:55)
connectivity_1   | Caused by: java.util.concurrent.TimeoutException: Futures timed out after [10000 milliseconds]
connectivity_1   | 	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:255)
connectivity_1   | 	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:259)
connectivity_1   | 	at scala.concurrent.Await$.$anonfun$result$1(package.scala:215)
connectivity_1   | 	at scala.concurrent.Await$$$Lambda$312.00000000A8DE0B10.apply(Unknown Source)
connectivity_1   | 	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
connectivity_1   | 	at scala.concurrent.Await$.result(package.scala:142)
connectivity_1   | 	at akka.remote.Remoting.start(Remoting.scala:194)
connectivity_1   | 	at akka.remote.RemoteActorRefProvider.init(RemoteActorRefProvider.scala:222)
connectivity_1   | 	at akka.cluster.ClusterActorRefProvider.init(ClusterActorRefProvider.scala:32)
connectivity_1   | 	at akka.actor.ActorSystemImpl.liftedTree2$1(ActorSystem.scala:826)
connectivity_1   | 	at akka.actor.ActorSystemImpl._start$lzycompute(ActorSystem.scala:823)
connectivity_1   | 	at akka.actor.ActorSystemImpl._start(ActorSystem.scala:823)
connectivity_1   | 	at akka.actor.ActorSystemImpl.start(ActorSystem.scala:842)
connectivity_1   | 	at akka.actor.ActorSystem$.apply(ActorSystem.scala:246)
connectivity_1   | 	at akka.actor.ActorSystem$.apply(ActorSystem.scala:289)
connectivity_1   | 	at akka.actor.ActorSystem$.apply(ActorSystem.scala:264)
connectivity_1   | 	at akka.actor.ActorSystem$.create(ActorSystem.scala:192)
connectivity_1   | 	at akka.actor.ActorSystem.create(ActorSystem.scala)
connectivity_1   | 	at org.eclipse.ditto.services.base.DittoService.createActorSystem(DittoService.java:275)
connectivity_1   | 	at org.eclipse.ditto.services.base.DittoService.doStart(DittoService.java:150)
connectivity_1   | 	at org.eclipse.ditto.services.base.DittoService$$Lambda$11.00000000A8812F00.call(Unknown Source)
connectivity_1   | 	at org.eclipse.ditto.services.base.MainMethodExceptionHandler.tryToRunMainMethodBody(MainMethodExceptionHandler.java:68)
connectivity_1   | 	... 3 more
connectivity_1   | 2018-10-03 20:03:57,805 INFO  [] a.r.RemoteActorRefProvider$RemotingTerminator akka://ditto-cluster/system/remoting-terminator - Shutting down remote daemon.
connectivity_1   | 2018-10-03 20:03:58,106 INFO  [] a.r.RemoteActorRefProvider$RemotingTerminator akka://ditto-cluster/system/remoting-terminator - Remote daemon shut down; proceeding with flushing remote transports.
connectivity_1   | 2018-10-03 20:03:58,398 ERROR [] akka.remote.Remoting akka.remote.Remoting - Remoting system has been terminated abrubtly. Attempting to shut down transports
connectivity_1   | 2018-10-03 20:03:58,398 ERROR [] akka.remote.Remoting akka.remote.Remoting - Remoting system has been terminated abrubtly. Attempting to shut down transports
connectivity_1   | 2018-10-03 20:03:58,493 INFO  [] akka.remote.Remoting akka.remote.Remoting - Remoting shut down
connectivity_1   | 2018-10-03 20:03:58,703 INFO  [] a.r.RemoteActorRefProvider$RemotingTerminator akka://ditto-cluster/system/remoting-terminator - Remoting shut down.
```
What is the cause of this issue?

**Comment by danielFesenmeyer** [comment]
I've never seen this error before and cannot reproduce it on my machine.
Maybe it happens when incompatible versions of the ditto microservices are used? Could you remove all ditto images and try it again?
`docker rmi -f $(docker images -q eclipse/ditto-*)`

Please let me know if it helps. If not,  I will further investigate this issue.

**Comment by RaiBnod** [comment]
No, I tried to up the ditto system by removing all images and building it fresh by:

**1.**
```
mvn clean install -Pdocker-build-image -Ddocker.daemon.url=unix:///var/run/docker.sock
cd deployment/docker/
docker-compose up -d
```
This wasn't working so I just tried it by:

**2.**
```
cd deployment/docker/
vim .env
```
_DITTO_VERSION=0.8.0-M2c_
```
docker-compose up -d
```
These both options are not working. Show this issue.

![screenshot from 2018-10-04 16-41-29](https://user-images.githubusercontent.com/6800775/46469873-6ed1f000-c7f4-11e8-9e43-6858f9f6f469.png)

**But similarly, I deployed the things on same fashion on another server and its working fine.**
**Note:** Both server meets the prequist.

**Docker version:** 18.06.1-ce
**Docker Compose version:** 1.22.0
**JDK version:** 1.8.0_92
**Maven:** 3.5.2

**Comment by danielFesenmeyer** [comment]
Thanks for the detailed information. I'm sorry, we still could not reproduce it.

I tested it on Windows and my colleague @thjaeckle on Linux, both with the same settings as specified by you (java and mvn version should be irrelevant):
*Docker version*: 18.06.1-ce
*Docker Compose version*: 1.22.0

I have just two ideas:
* After you started docker-compose, a network with the name "docker_default" should have been created. Can you please have a look? `docker network ls` should return sth like this:
...
6949ff101f37        docker_default                 bridge              local
...
* Maybe your machine just needs some more time to start the remoting. You could try to increase _akka.remote.startup-timeout_ (default: 10s). For this purpose change the _IBM_JAVA_OPTIONS_ everywhere in docker-compose.yml like this:
IBM_JAVA_OPTIONS=-XX:+ExitOnOutOfMemoryError -Dakka.remote.startup-timeout=60s

**Comment by RaiBnod** [comment]
- Yes `docker_default` was created after doing docker-compose up.

![screenshot from 2018-10-04 22-43-51](https://user-images.githubusercontent.com/6800775/46490298-5deea200-c827-11e8-9b59-b7a6e1e7d409.png)

- Tried after increasing that startup-timeout to `60s` too, but it didn't help me. Please find additional logs which may help to know the cause of this issue (this is the log after we get TimeoutException attached in previous comment chain):
![screenshot from 2018-10-04 22-45-49](https://user-images.githubusercontent.com/6800775/46490519-e79e6f80-c827-11e8-9de2-c8206f5ffe72.png)

**Comment by danielFesenmeyer** [comment]
The logs show that the containers cannot access each other on port 2551 inside the network "docker_default". I just wondered if there was some problem with your host firewall configuration, but this does not make sense because the host firewall should not affect the communication between containers. So, it seems that there is some problem with your docker installation.

Maybe you can reproduce this issue with a simple example: create a bridge network, add two containers and try to access one of the containers from the other container via tcp (e.g. with netcat).

Probably the docker gurus here can help to further analyse this issue: https://forums.docker.com/.

**Comment by danielFesenmeyer** [comment]
@RaiBnod: Do you still have this issue?

To be able to support you, we should know whether you could reproduce the issue with a simple tcp example. This is important for us to figure out whether it is a Docker or Akka problem.

**Comment by RaiBnod** [comment]
Hey @danielFesenmeyer: That's issue is only on my local computer, tried many times by removing and re-composing the images but didn't work for me. But, the same thing I did on a server is working fine.

Moreover, On the server where I deployed the ditto, services got exited repeatedly and need to hit command **'docker-compose up -d'** again and again.

![screenshot from 2018-10-10 15-39-47](https://user-images.githubusercontent.com/6800775/46730486-01b4d380-cca8-11e8-921a-275bc5d24ed4.png)

As in the above screenshot, some services are running from 45 hours, some of them from 4 hours and one service which is just got exited.

**Comment by danielFesenmeyer** [comment]
Hey @RaiBnod.

For analysing your local computer problem, it would really help if you could reproduce the issue with a simple tcp example.

On your server there seems to be a different issue. To support with this, we would need the complete docker logs (_docker-compose logs_). Maybe you can attach them here? Just from the status of the services, it is difficult to guess the root cause..

**Comment by danielFesenmeyer** [comment]
Closing this issue due to inactivity.

**Comment by sergiomanso** [comment]
I'm having the exact same problem.

I'm using ditto 0.8.0 and happens the same as in the first post. (Tried with docker 18.09 and 18.06)

I increased the startup-timeout (60s) and docker-compose logs spit this:

https://pastebin.com/wc27z26x

After this containers started to exit.
