### ISSUE TITLE
Full cluster failure - AskTimeoutException, IndexOptionsConflict, multiple timeouts

### ISSUE THREAD

**Issue by w4tsn** [eclipse/ditto#621]
At the moment I'm observing re-occuring AskTimeoutExceptions in the concierge service which causes all other services and requests from both connecitivty as well as gateway to fail.

I have no idea whats going on and if this might be a general problem of the cluster degrading over time or if it's just my setup that is screwed up.

This error is accompanied by a lot of time out error throughout the cluster.

The gateway server is responding with `No response within server request timeout (<PT1M>), shutting actor down.` and nginx follows with 503 for the original PUT request.

The things service emitts strange messages with type SudoStreamModifiedEntities and start and end dates somewhere in 2001.

What is also alarming is a mongodb error thrown in the things service `IndexOptionsConflict: things_snaps_index already exists with different options`

I noticed that it started working again after some time this morning after a reboot. I had to wait a couple of minutes until the error messages dissapeared and the cluster seemed to work properly. Then after another reboot later this day, the cluster started having problems again and did not recover ever since.

The error messages supplied below are a reoccuring pattern.

**Edit 1:** after about 10 to 30 Minutes the cluster seems to catch itself and works again. When restarting it then takes a lot of time again for the system to recover a stable state.

Setup / Environment
---

docker-compose based setup.

Ditto version 1.0.0, official images

Slight configuration changes in message-max-size and akka buffer sizes.

The cluster started at ditto 0.8.0 and lived through two database migrations, which I applied as stated in the documentation.

I had problems with the migration from 0.9.0 to 1.0.0, hence applying the operations manually based off of the supplied script in the documentation. It worked out for several months until now.

The VM running the docker-compose setup has 16 Gig of RAM and 4 CPUs. Ditto raises the CPU load15 to around 5 on average and 8 on startup.

Logs
---

**Concierge service log**

```
concierge_1      | 2020-02-25 15:38:18,599 ERROR [ecb557b3-7260-4f18-bef9-d8049b16fcc3] o.e.d.s.c.e.EnforcerActor akka://ditto-cluster/user/conciergeRoot/enforcer - Unexpected non-DittoRuntimeException error - responding with GatewayInternalErrorException - AskTimeoutException :Ask timed out on [Actor[akka://ditto-cluster/system/sharding/thingProxy#-6024026]] after [30000 ms]. Message of type [org.eclipse.ditto.services.models.things.commands.sudo.SudoRetrieveThing]. A typical reason for `AskTimeoutException` is that the recipient actor didn't send a reply.
concierge_1      | akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka://ditto-cluster/system/sharding/thingProxy#-6024026]] after [30000 ms]. Message of type [org.eclipse.ditto.services.models.things.commands.sudo.SudoRetrieveThing]. A typical reason for `AskTimeoutException` is that the recipient actor didn't send a reply.
concierge_1      | 	at akka.pattern.PromiseActorRef$.$anonfun$defaultOnTimeout$1(AskSupport.scala:648)
concierge_1      | 	at akka.pattern.PromiseActorRef$$$Lambda$258.00000000E527C670.apply(Unknown Source)
concierge_1      | 	at akka.pattern.PromiseActorRef$.$anonfun$apply$1(AskSupport.scala:669)
concierge_1      | 	at akka.pattern.PromiseActorRef$$$Lambda$259.00000000E527D380.apply$mcV$sp(Unknown Source)
concierge_1      | 	at akka.actor.Scheduler$$anon$4.run(Scheduler.scala:202)
concierge_1      | 	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:875)
concierge_1      | 	at scala.concurrent.BatchingExecutor.execute(BatchingExecutor.scala:113)
concierge_1      | 	at scala.concurrent.BatchingExecutor.execute$(BatchingExecutor.scala:107)
concierge_1      | 	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:873)
concierge_1      | 	at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(LightArrayRevolverScheduler.scala:334)
concierge_1      | 	at akka.actor.LightArrayRevolverScheduler$$anon$3.executeBucket$1(LightArrayRevolverScheduler.scala:285)
concierge_1      | 	at akka.actor.LightArrayRevolverScheduler$$anon$3.nextTick(LightArrayRevolverScheduler.scala:289)
concierge_1      | 	at akka.actor.LightArrayRevolverScheduler$$anon$3.run(LightArrayRevolverScheduler.scala:241)
concierge_1      | 	at java.lang.Thread.run(Unknown Source)
```

**Things service log**

```
things_1         | 2020-02-25 16:22:46,259 INFO  [] o.e.d.s.u.p.m.DefaultPersistenceStreamingActor akka://ditto-cluster/user/thingsRoot/persistenceStreamingActor - Starting stream for <SudoStreamModifiedEntities [type=streaming:org.eclipse.ditto.services.models.streaming.SudoStreamModifiedEntities, dittoHeaders=ImmutableDittoHeaders [{}], start=2001-03-18T09:45:45Z, end=2001-03-18T09:50:50Z, burst=10, timeoutMillis=600000]>
```

**Things service log (mongodb)**

```
things_1         | 2020-02-25 16:29:07,284 ERROR [] o.e.d.s.t.p.a.ThingPersistenceActor akka://ditto-cluster/system/sharding/thing/18/c0011%3A1E021EBF6658E6B7/pa - Got SaveSnapshotFailure(SnapshotMetadata(thing:c0011:1E021EBF6658E6B7,565,0),com.mongodb.MongoCommandException: Command failed with error 85 (IndexOptionsConflict): 'Index with name: things_snaps_index already exists with different options' on server mongodb:27017. The full response is {"ok": 0.0, "errmsg": "Index with name: things_snaps_index already exists with different options", "code": 85, "codeName": "IndexOptionsConflict"})
things_1         | com.mongodb.MongoCommandException: Command failed with error 85 (IndexOptionsConflict): 'Index with name: things_snaps_index already exists with different options' on server mongodb:27017. The full response is {"ok": 0.0, "errmsg": "Index with name: things_snaps_index already exists with different options", "code": 85, "codeName": "IndexOptionsConflict"}
things_1         | 	at com.mongodb.internal.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:175)
things_1         | 	at com.mongodb.internal.connection.InternalStreamConnection$2$1.onResult(InternalStreamConnection.java:390)
things_1         | 	at com.mongodb.internal.connection.InternalStreamConnection$2$1.onResult(InternalStreamConnection.java:376)
things_1         | 	at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback$MessageCallback.onResult(InternalStreamConnection.java:677)
things_1         | 	at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback$MessageCallback.onResult(InternalStreamConnection.java:644)
things_1         | 	at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:514)
things_1         | 	at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:511)
things_1         | 	at com.mongodb.internal.connection.AsynchronousChannelStream$BasicCompletionHandler.completed(AsynchronousChannelStream.java:220)
things_1         | 	at com.mongodb.internal.connection.AsynchronousChannelStream$BasicCompletionHandler.completed(AsynchronousChannelStream.java:203)
things_1         | 	at sun.nio.ch.Invoker.invokeUnchecked(Unknown Source)
things_1         | 	at sun.nio.ch.Invoker.invokeDirect(Unknown Source)
things_1         | 	at sun.nio.ch.UnixAsynchronousSocketChannelImpl.implRead(Unknown Source)
things_1         | 	at sun.nio.ch.AsynchronousSocketChannelImpl.read(Unknown Source)
things_1         | 	at sun.nio.ch.AsynchronousSocketChannelImpl.read(Unknown Source)
things_1         | 	at com.mongodb.internal.connection.AsynchronousSocketChannelStream$AsynchronousSocketChannelAdapter.read(AsynchronousSocketChannelStream.java:137)
things_1         | 	at com.mongodb.internal.connection.AsynchronousChannelStream.readAsync(AsynchronousChannelStream.java:105)
things_1         | 	at com.mongodb.internal.connection.InternalStreamConnection.readAsync(InternalStreamConnection.java:511)
things_1         | 	at com.mongodb.internal.connection.InternalStreamConnection.access$1000(InternalStreamConnection.java:76)
things_1         | 	at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback.onResult(InternalStreamConnection.java:634)
things_1         | 	at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback.onResult(InternalStreamConnection.java:619)
things_1         | 	at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:514)
things_1         | 	at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:511)
things_1         | 	at com.mongodb.internal.connection.AsynchronousChannelStream$BasicCompletionHandler.completed(AsynchronousChannelStream.java:220)
things_1         | 	at com.mongodb.internal.connection.AsynchronousChannelStream$BasicCompletionHandler.completed(AsynchronousChannelStream.java:203)
things_1         | 	at sun.nio.ch.Invoker.invokeUnchecked(Unknown Source)
things_1         | 	at sun.nio.ch.Invoker.invokeDirect(Unknown Source)
things_1         | 	at sun.nio.ch.UnixAsynchronousSocketChannelImpl.implRead(Unknown Source)
things_1         | 	at sun.nio.ch.AsynchronousSocketChannelImpl.read(Unknown Source)
things_1         | 	at sun.nio.ch.AsynchronousSocketChannelImpl.read(Unknown Source)
things_1         | 	at com.mongodb.internal.connection.AsynchronousSocketChannelStream$AsynchronousSocketChannelAdapter.read(AsynchronousSocketChannelStream.java:137)
things_1         | 	at com.mongodb.internal.connection.AsynchronousChannelStream.readAsync(AsynchronousChannelStream.java:105)
things_1         | 	at com.mongodb.internal.connection.InternalStreamConnection.readAsync(InternalStreamConnection.java:511)
things_1         | 	at com.mongodb.internal.connection.InternalStreamConnection.access$1000(InternalStreamConnection.java:76)
things_1         | 	at com.mongodb.internal.connection.InternalStreamConnection$2.onResult(InternalStreamConnection.java:376)
things_1         | 	at com.mongodb.internal.connection.InternalStreamConnection$2.onResult(InternalStreamConnection.java:365)
things_1         | 	at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:49)
things_1         | 	at com.mongodb.internal.connection.InternalStreamConnection$3.completed(InternalStreamConnection.java:468)
things_1         | 	at com.mongodb.internal.connection.InternalStreamConnection$3.completed(InternalStreamConnection.java:465)
things_1         | 	at com.mongodb.internal.connection.AsynchronousChannelStream$1.completed(AsynchronousChannelStream.java:91)
things_1         | 	at com.mongodb.internal.connection.AsynchronousChannelStream$1.completed(AsynchronousChannelStream.java:85)
things_1         | 	at com.mongodb.internal.connection.AsynchronousChannelStream$2.completed(AsynchronousChannelStream.java:167)
things_1         | 	at com.mongodb.internal.connection.AsynchronousChannelStream$2.completed(AsynchronousChannelStream.java:161)
things_1         | 	at com.mongodb.internal.connection.AsynchronousChannelStream$AsyncWritableByteChannelAdapter$WriteCompletionHandler.completed(AsynchronousChannelStream.java:192)
things_1         | 	at com.mongodb.internal.connection.AsynchronousChannelStream$AsyncWritableByteChannelAdapter$WriteCompletionHandler.completed(AsynchronousChannelStream.java:183)
things_1         | 	at sun.nio.ch.Invoker.invokeUnchecked(Unknown Source)
things_1         | 	at sun.nio.ch.Invoker$2.run(Unknown Source)
things_1         | 	at sun.nio.ch.AsynchronousChannelGroupImpl$1.run(Unknown Source)
things_1         | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
things_1         | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
things_1         | 	at java.lang.Thread.run(Unknown Source)
```

**Full log (about 10 minutes)**: [ditto_cluster_errors.txt](https://github.com/eclipse/ditto/files/4250833/ditto_cluster_errors.txt)

**Comment by thjaeckle** [comment]
Hi @w4tsn 
That index exception `Index with name: things_snaps_index already exists with different options` sounds really strange.
Did you try dropping the index `things_snaps_index`? It should be automatically recreated.

That could in fact cause the timeout exception you are seeing in the logs.
However I really have no idea why this should come "out of the blue".
Could it be that those errors exist since updating to Ditto 1.0.0?

**Comment by w4tsn** [comment]
Thanks @thjaeckle,

this solved the problem indeed. I don't know why it just started to fail out of the blue. We are utilizing the cluster more since a few weeks and I did not have to restart it for a while. Since it seems that this mostly impacted the start procedure and "healed" off after around 30 minutes it might have not caught my attention earlier.
