### ISSUE TITLE
Concierge cannot access another actor

### ISSUE THREAD

**Issue by fxulusoy** [eclipse/ditto#762]
I have a ditto instance running on the Kubernetes and all the pods are running fine. Everything was working before. There can be some changes regarding to the users but I am not sure how it can cause this error. 
I receive the following error message when I call the things API endpoint (`api/2/things/<my_thing_id>`) on Ditto:

```
{
  "status": 500,
  "error": "gateway:internalerror",
  "message": "There was a rare case of an unexpected internal error.",
  "description": "Please contact the service team."
}
```

These logs are from ditto-congierce service. As far as I understand that the congierce service cannot access one of other actor. But I am not sure which one is it. I guess, it is the thing service. What else should I check?

```
2020-08-12 16:10:28,030 ERROR [c06a3803-5ca4-487c-a528-7019991777f6] o.e.d.s.c.e.EnforcerActor akka://ditto-cluster/user/conciergeRoot/enforcer - Unexpected non-DittoRuntimeException error - responding with GatewayInternalErrorException - AskTimeoutException :Ask timed out on [Actor[akka://ditto-cluster/system/sharding/thingProxy#-878452685]] after [30000 ms]. Message of type [org.eclipse.ditto.services.models.things.commands.sudo.SudoRetrieveThing]. A typical reason for `AskTimeoutException` is that the recipient actor didn't send a reply.
akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka://ditto-cluster/system/sharding/thingProxy#-878452685]] after [30000 ms]. Message of type [org.eclipse.ditto.services.models.things.commands.sudo.SudoRetrieveThing]. A typical reason for `AskTimeoutException` is that the recipient actor didn't send a reply.
	at akka.pattern.PromiseActorRef$.$anonfun$defaultOnTimeout$1(AskSupport.scala:648)
	at akka.pattern.PromiseActorRef$$$Lambda$251.00000000DD12D5B0.apply(Unknown Source)
	at akka.pattern.PromiseActorRef$.$anonfun$apply$1(AskSupport.scala:669)
	at akka.pattern.PromiseActorRef$$$Lambda$252.00000000DD14DE20.apply$mcV$sp(Unknown Source)
	at akka.actor.Scheduler$$anon$4.run(Scheduler.scala:202)
	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:875)
	at scala.concurrent.BatchingExecutor.execute(BatchingExecutor.scala:113)
	at scala.concurrent.BatchingExecutor.execute$(BatchingExecutor.scala:107)
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:873)
	at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(LightArrayRevolverScheduler.scala:334)
	at akka.actor.LightArrayRevolverScheduler$$anon$3.executeBucket$1(LightArrayRevolverScheduler.scala:285)
	at akka.actor.LightArrayRevolverScheduler$$anon$3.nextTick(LightArrayRevolverScheduler.scala:289)
	at akka.actor.LightArrayRevolverScheduler$$anon$3.run(LightArrayRevolverScheduler.scala:241)
	at java.lang.Thread.run(Unknown Source)
2020-08-12 16:10:28,237 WARN [] a.c.s.ShardRegion akka://ditto-cluster@10.244.2.82:2551/system/sharding/thingProxy - thing: No coordinator found to register. Probably, no seed-nodes configured and manual cluster join not performed? Total [8] buffered messages.
2020-08-12 16:10:30,238 WARN [] a.c.s.ShardRegion akka://ditto-cluster@10.244.2.82:2551/system/sharding/thingProxy - thing: No coordinator found to register. Probably, no seed-nodes configured and manual cluster join not performed? Total [8] buffered messages.
2020-08-12 16:10:32,238 WARN [] a.c.s.ShardRegion akka://ditto-cluster@10.244.2.82:2551/system/sharding/thingProxy - thing: No coordinator found to register. Probably, no seed-nodes configured and manual cluster join not performed? Total [8] buffered messages.
```

**Comment by thjaeckle** [comment]
Are you sure that the Ditto cluster is in a healthy state?
Does not seem like it ..
Did you check the `/status/health` HTTP endpoint of Ditto's `gateway` service? This should aggregate to `UP` - I would guess that this is not the case.
