### ISSUE TITLE
Import package configuration line breaks OSGi compatibility of Ditto JSON

### ISSUE THREAD

**Issue by kaloyanrradev** [eclipse/ditto#790]
Please check this line in the maven-bundle-plugin config of the Ditto JSON client bundle:

https://github.com/eclipse/ditto/blob/1ba630b5f07086c9a5127ef9a5b3a28650bc8343/json/pom.xml#L176

It needs to be cleared or extended with a star in the end, otherwise it will hide (not import) the Jackson packages used:

`<Import-Package>com.eclipsesource.json,*</Import-Package>`

Currently the single imported package actually allows the bundle to be resolved in OSGi environments, but it will actually have a ClassNotFound exception once it tries to uses most of its functionality (unless the class is loaded by the caller code).

**Comment by thjaeckle** [comment]
Hi.
Jackson should not be a required dependency for Ditto-json. It's only used in Ditto's backend for doing CBOR serialization.
When not available on the classpath, Ditto-json should still work. 
Do you have a stack trace where the Jackson class is being loaded?

**Comment by thjaeckle** [comment]
Probably we did something wrong here.

ditto-json in fact has imports to `com.fasterxml.jackson.core` and `com.fasterxml.jackson.dataformat.cbor` - however catches a `NoClassDefFoundError` when they can't be loaded during runtime.

See https://github.com/eclipse/ditto/blob/master/json/src/main/java/org/eclipse/ditto/json/CborAvailabilityChecker.java#L38-L48

This `CborAvailabilityChecker` is used in both JsonObject and JsonArray implementations.
We somehow need to dynamically determine and load the CBOR classes - but in OSGi environments that could get tricky. Will have to investigate ...

**Comment by thjaeckle** [comment]
We're working on it.
Goal is to ship "ditto-json" with no dependency to any Jackson library, also not in scope of OSGi "imports".

**Comment by thjaeckle** [comment]
@kaloyanrradev how exactly did you produce this error?
We're wondering as this change is already in ditto-json since Ditto 1.1.0 which was released in April this year.
And we just tried out using the ditto-client 1.1.0 and 1.2.0 (which uses ditto-json as well) in a Felix container which worked.

**Comment by desislava-marinova** [comment]
@thjaeckle, as we used ditto 1.0.0 and we had no such issues, in ditto 1.1.5 the problem is also experienced. 

Is the following stack trace helpful? 
`Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.core.JsonFactory, from bundle org.eclipse.ditto.json
	at com.prosyst.mbs.impl.framework.DefaultClassProvider.loadClass_(DefaultClassProvider.java:603) ~[?:?]
	at com.prosyst.mbs.impl.framework.DefaultClassProvider.loadClass(DefaultClassProvider.java:453) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_171]
	at org.eclipse.ditto.json.ImmutableJsonArray$SoftReferencedValueList.parseToList(ImmutableJsonArray.java:409) ~[?:?]
	at org.eclipse.ditto.json.ImmutableJsonArray$SoftReferencedValueList.recoverValues(ImmutableJsonArray.java:394) ~[?:?]
	at org.eclipse.ditto.json.ImmutableJsonArray$SoftReferencedValueList.values(ImmutableJsonArray.java:386) ~[?:?]
	at org.eclipse.ditto.json.ImmutableJsonArray$SoftReferencedValueList.getStream(ImmutableJsonArray.java:422) ~[?:?]
	at org.eclipse.ditto.json.ImmutableJsonArray.stream(ImmutableJsonArray.java:249) ~[?:?]
	at org.eclipse.ditto.model.base.headers.AbstractDittoHeaders.getAcknowledgementRequests(AbstractDittoHeaders.java:308) ~[?:?]
	at org.eclipse.ditto.client.internal.AbstractHandle.validateAckRequests(AbstractHandle.java:263) ~[?:?]
	at org.eclipse.ditto.client.internal.AbstractHandle.askThingCommand(AbstractHandle.java:167) ~[?:?]
	at org.eclipse.ditto.client.management.internal.FeatureHandleImpl.retrieve(FeatureHandleImpl.java:130) ~[?:?]
	at com.bosch.iot.dm.devices.remote.impl.DeviceInventoryRemoteImpl.lambda$null$16(DeviceInventoryRemoteImpl.java:387) ~[?:?]
	at com.bosch.iot.dm.async.CompletableFuture.lambda$null$24(CompletableFuture.java:973) ~[?:?]
	at com.bosch.iot.dm.auth.AuthCtx.callWithMDCSubscrId(AuthCtx.java:300) ~[?:?]
	at com.bosch.iot.dm.auth.AuthCtx.callWithMDCAuthCtx(AuthCtx.java:280) ~[?:?]
	at com.bosch.iot.dm.auth.AuthCtx.callAs(AuthCtx.java:239) ~[?:?]
	at com.bosch.iot.dm.auth.AuthCtx.callAs(AuthCtx.java:216) ~[?:?]
	at com.bosch.iot.dm.async.CompletableFuture.lambda$authCtxAware$25(CompletableFuture.java:973) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952) ~[?:1.8.0_171]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926) ~[?:1.8.0_171]
	... 51 more`

**Comment by thjaeckle** [comment]
@desislava-marinova yes, this helps - thanks 👍

**Comment by thjaeckle** [comment]
Ok, our fix in PR #793 will fix that, of that I'm certain.

**Comment by thjaeckle** [comment]
Released as part of Ditto 1.2.1: https://www.eclipse.org/ditto/release_notes_121.html
Artifacts were published to Maven central which should have them available very soon.

**Comment by kaloyanrradev** [comment]
Hi @thjaeckle, applogies for the late response - I was on a vacation last few days and many thanks for the quick reaction and fix!
